### ISSUE TITLE
Terraform creating duplicate openstack_lb_pool_v2 entries

### ISSUE THREAD

**Issue by robert-cam** [terraform-providers/terraform-provider-openstack#110]
### Terraform Version
Terraform v0.10.4

### Affected Resource(s)
Please list the resources as a list, for example:
openstack_lb_pool_v2

### Terraform Configuration Files
https://www.dropbox.com/s/pr8gm7qbla7sc4l/duplicate-pool.tf.gpg?dl=0

### Debug Output
Create output: https://gist.github.com/robert-cam/4323462c58aa6cce3e2c599856012621
Destroy output: https://gist.github.com/robert-cam/4321eddaf4ceca17a7b37e051a088bd0

### Expected Behavior
There should have been the same number of lbaas pools created in neutron as existed in the config.

### Actual Behavior
Extra pools were created which "terraform destroy" does not remove.
Removing these manually with the neutron command line client allows the destroy to continue and finish.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Create a config with two lbaas pools with two members per pool
2. `terraform apply`
3. list pools: `neutron lbaas-pool-list`
4. `terraform destroy`

**Comment by jtopjian** [comment]
@robert-cam which version of the Terraform OpenStack plugin are you using? The one provided when you run `terraform init` or one compiled from source?

**Comment by robert-cam** [comment]
@jtopjian compiled with source with the fix for https://github.com/terraform-providers/terraform-provider-openstack/issues/98, last commit on my compiled version was adeb4528f48b75ff13482198159af1f3aa51e32b.

**Comment by jtopjian** [comment]
@robert-cam Thanks! I will take a look and see if I can figure out what's going on.

**Comment by jtopjian** [comment]
@robert-cam Where can I find the public key to decrypt the gpg file? Is is the same configuration as in #98?

**Comment by robert-cam** [comment]
@jtopjian apologies, I've added the public key to my profile now. It's basically the same config but I've tried to strip it down to the minimum to duplicate this problem.

**Comment by jtopjian** [comment]
@robert-cam What's the URL to access your GPG key? I'm unable to view it on your profile page and some basic Github API URLs aren't showing it either.

**Comment by robert-cam** [comment]
@jtopjian sorry, I'm new to github and I haven't been able to work that out so I've just uploaded an unencrypted copy to https://www.dropbox.com/s/yug3y95zs93lmu9/duplicate-pool.tf?dl=0

**Comment by jtopjian** [comment]
@robert-cam no problem at all.

I downloaded the config and modified it _slightly_: I changed the region, external gateway, flavor, and image. Other than that, same config. I launched it in my test environment (which is a vanilla/standard OpenStack Ocata environment, using standard plugins and drivers) and wasn't able to reproduce the problem. 

From reviewing your config, it seems like every time a pool attempts to be created but receives a 409 from Neutron (meaning, the load balancer is still updating from the previous request), a pool is created anyways. I'm not seeing that with my environment.

I have a few questions:

1. Do you know what version of OpenStack your cloud environment is running?
2. Can you try running `terraform apply -parallelism=1`? This will make Terraform build all resources one at a time, rather than build resources in parallel when it can. Let me know if that makes a difference.
3. Does the same behavior happen if you build all of these resources using the `openstack`, `neutron`, and `nova` command-line tools?

**Comment by robert-cam** [comment]
1. We're running Openstack Newton.
2. This does not happen with `terraform apply -parallelism=1`
3. I cannot duplicate this with the Openstack command line tools

**Comment by jtopjian** [comment]
OK, good to know that it doesn't happen with `parallelism` set to `1` - that at least provides a workaround.

> I cannot duplicate this with the Openstack command line tools

Have you tried setting it up so that two pools are created in rapid-succession or parallel? Like add the commands to create the pool to a bash script such as:

```shell
neutron lbaas-pool-create ... &
neutron lbaas-pool-create ... &
```

using `&` to immediately run in the background.

I just want to try to see if this behavior is native to your OpenStack environment. Since I'm not able to reproduce this issue, it's hard for me to try to pin down.

**Comment by robert-cam** [comment]
I've tried that now and I get two pools created:
`
Created a new pool:
+---------------------+------------------------------------------------+
| Field               | Value                                          |
+---------------------+------------------------------------------------+
| admin_state_up      | True                                           |
| description         |                                                |
| healthmonitor_id    |                                                |
| id                  | 57a8c184-796b-48f2-8181-1f2d134cfbd4           |
| lb_algorithm        | SOURCE_IP                                      |
| listeners           | {"id": "f5434718-ef48-4bcb-be47-141b9eddf23b"} |
| loadbalancers       | {"id": "c88bf877-13f8-457a-a7d5-f488c3c78abc"} |
| members             |                                                |
| name                | https                                          |
| protocol            | HTTPS                                          |
| session_persistence |                                                |
| tenant_id           | cd20dd7ba3cb4aa4aad0b034474b0bb6               |
+---------------------+------------------------------------------------+
Created a new pool:
+---------------------+------------------------------------------------+
| Field               | Value                                          |
+---------------------+------------------------------------------------+
| admin_state_up      | True                                           |
| description         |                                                |
| healthmonitor_id    |                                                |
| id                  | a3e6f4aa-07c2-47c3-ba15-50c4df1604a6           |
| lb_algorithm        | SOURCE_IP                                      |
| listeners           | {"id": "190a8011-921e-49bf-911f-afeacaa2f501"} |
| loadbalancers       | {"id": "c88bf877-13f8-457a-a7d5-f488c3c78abc"} |
| members             |                                                |
| name                | http                                           |
| protocol            | HTTP                                           |
| session_persistence |                                                |
| tenant_id           | cd20dd7ba3cb4aa4aad0b034474b0bb6               |
+---------------------+------------------------------------------------+
`

**Comment by robert-cam** [comment]
@jtopjian our Openstack admins have just told me this is an issue in Openstack Newton that's fixed in Okata. Thanks for your help with this!

**Comment by friegger** [comment]
@robert-cam For reference, I assume you're probably talking about https://review.openstack.org/#/c/420302/.

**Comment by robert-cam** [comment]
@friegger they didn't give me a link or bug number but that sounds like exactly what I was seeing.
