### ISSUE TITLE
Disable network port security option in Openstack through terraform

### ISSUE THREAD

**Issue by jayaprakashr** [terraform-providers/terraform-provider-openstack#161]
On-boarding of VNF requires OpenStack network port security option to be disabled which is not possible currently. Could you please fix this or let me know if any workaround option is available to achieve the same. 

```
{
                "openstack_networking_port_v2": {
                        "ctrl_NETWORK": {
                                "name": "ctrl_NETWORK",
                                "network_id": "${var.VERSA_MGMT_NETWORK_ID}",
                                "fixed_ip": {
                                        "subnet_id": "${var.subnet_VERSA_MGMT_NETWORK}",
                                        "ip_address": "${var.Controller_VERSA_MGMT_NETWORK_IP}"
                                },
                                "admin_state_up": "true"
                        }
                }

```

**Comment by fatmcgav** [comment]
@jayaprakashr It should be possible to do this by setting `no_security_group: true`. See https://www.terraform.io/docs/providers/openstack/r/networking_port_v2.html#no_security_groups for more info.

**Comment by jayaprakashr** [comment]
@fatmcgav  
I tried that also, but it doesn't works. 
Just now I saw an another ticket on the same - https://github.com/terraform-providers/terraform-provider-openstack/issues/22 
if this is not fixed yet in terraform, is there any workaround possible ??

**Comment by jtopjian** [comment]
Hi all,

Correct, Terraform / Gophercloud need support for port security which is something I've been working on. It was delayed for a number of months due to some limitations it uncovered in Gophercloud.

There is a work around, though this is most definitely a work around and not supported:, use the `value_specs` argument. In the Terraform OpenStack provider, `value_specs` are a way of injecting extra key/value pairs into the create request to help with random vendor-specific data. It can also be used to inject information not yet supported in Terraform or Gophercloud.

So you can do:

```hcl
value_specs {
  port_security_enabled = false
}
```

Please be aware that this will only work for creating and not updating. In addition, this is not an officially supported way of doing this.

Hope that helps

**Comment by jtopjian** [comment]
I'm going to close this issue since #22 is tracking progress on the official implementation. But please let me know if you have any other questions.

**Comment by jayaprakashr** [comment]
Thanks @jtopjian 
Workaround provided to use value_specs option works well. I'm good as of now until it is officially supported in terraform/Gophercloud. 

> Please be aware that this will only work for creating and not updating. In addition, this is not an officially supported way of doing this.

This option even works well when we do a resource update. I have verified the below two cases and in both cases, plan/apply works as expected. 
**Case:1**
      value_specs.%:                     "" => "1" (forces new resource)
      value_specs.port_security_enabled: "" => "false" (forces new resource)
**Case:2**
      value_specs.port_security_enabled: "false" => "true" (forces new resource)
