### ISSUE TITLE
The Openlab CI system integration request

### ISSUE THREAD

**Issue by liu-sheng** [terraform-providers/terraform-provider-openstack#181]
I'd like to introduce a CI system "Openlab" into Terraform-provider-openstack. The Openlab CI system is built based on [zuul](https://docs.openstack.org/infra/zuul/) and [nodepool](https://docs.openstack.org/infra/nodepool/) tools and some other components, it is for running tests of OpenStack SDKs (e.g. Gophercloud, Terraform) based on a [devstack](https://docs.openstack.org/devstack/latest/) environment. For more details about Openlab, please see [here](http://openlabtesting.org/). We have  done the integration of Openlab CI and Gophercloud in [PR](https://github.com/gophercloud/gophercloud/pull/593). For now, the CI system can also basically work OK with Terraform-provider-openstack, see [here](https://github.com/theopenlab/terraform-provider-openstack/pull/2). We will long-term maintain the CI system and would like to integrate the CI system to Terraform-provider-openstack official repo.

FYI, the zuul jobs definition is in [here](https://github.com/theopenlab/openlab-zuul-jobs), the zuul jobs status web page is in [here](http://status.openlabtesting.org/), the logs of testing jobs is in [here](http://logs.openlabtesting.org/logs/).

If it is possible to integrate this CI system with Terraform-provider-openstack official repo, there are two things need to to with Terraform-provider-openstack repo to integrate with this CI system:
a). Need to install a [github app](https://github.com/apps/theopenlab-ci) for triggering the CI jobs.
b). Need to add a ".zuul.yaml" file as a CI jobs entrypoint into the terraform-provider-openstack repo.
There is a simple guide for integration Openlab CI, please see [here](https://github.com/theopenlab/cicd-howto#connect-to-openlab)

Thanks.

**Comment by jtopjian** [comment]
@apparentlymart Sorry to ping you on this - please feel free to forward / share this with anyone else who should be part of this discussion. This is different than the discussion we had about vexxhost.

@liu-sheng has given some great background on this. The high level summary is that if we integrate OL testing with this git repo, it will provide full acceptance testing for a matrix of OpenStack releases automatically on _each_ pull request / commit. They've taken what I've done with the existing nightly CI tests and made it awesome. The OL team has been working on getting this running for a few weeks with a forked copy of this provider.

We (Gophercloud) worked with OL to do this for Gophercloud. You can see an example of it in action [here](https://github.com/gophercloud/gophercloud/pull/638#issuecomment-348394132). 

In order to get this working, I'll need to merge #182. After that, someone from core will need to add the TheOpenLab-CI github app to this repo. Instructions for that are [here](https://github.com/theopenlab/cicd-howto#connect-to-openlab). 

I'm more than happy to be a point of communication between the two parties as well as look over maintenance of this integration. Also happy to discuss this more in Slack. I won't proceed with this until I've gotten clearance. :)

@liu-sheng Thank you for submitting this and for you and your team's help with prepping for this. :)

**Comment by liu-sheng** [comment]
@jtopjian Thank you for help to promote this proposal :). And would @apparentlymart and terraform-provider-openstack team please help to review this, please raise if you have any question.

Thanks a lot.

**Comment by jtopjian** [comment]
Implemented in #182 

@liu-sheng Thank you and your team for your help with this. :smile:
