### ISSUE TITLE
Feature request: data source: data.openstack_compute_flavor

### ISSUE THREAD

**Issue by Nowaker** [terraform-providers/terraform-provider-openstack#187]
The purpose of this data source is to search for the flavor by RAM, vCPUs or whatever. Similar to `openstack_images_image`.

API end-point: `/api/nova/flavors/?get_extras=true&is_public=true`
Example JSON response: https://gist.github.com/Nowaker/48a3d98a3e8850d5f742ccdbffb7401b

Example:
```hcl
data "openstack_compute_flavor_v2" "2gbram" {
  cheapest_matching = true
  properties {
    vcpus = "2"
    ram = "2048"
  }
}

resource "openstack_compute_instance_v2" "instance" {
  # ...
  flavor_id = "${data.openstack_compute_flavor_v2.2gbram.id}"
  image_name = "${data.openstack_images_image_v2.image.name}"
  # ...
}
```

How does it sound?

**Comment by jtopjian** [comment]
@Nowaker This is definitely possible, though cloud-specific parameters such as `cheapest_matching` aren't possible. From the JSON response you gave, this seems to be supported in DreamCompute, but that's only because it's specified as an "extra" field (which are arbitrary key/value pairs). 

Querying for arbitrary extra fields should be possible, though.

**Comment by jtopjian** [comment]
@Nowaker I've opened #190 which adds this data source. It supports all query-able fields possible at this time.

If you're able to test this, feedback would be most welcomed.

Please let me know if you have any questions or comments.

**Comment by Nowaker** [comment]
Wow, great! Many thanks. I'll give it a shot on Monday. Take care!

**Comment by Nowaker** [comment]
@jtopjian Works like a charm for me! Thank you!
