### ISSUE TITLE
openstack_networking_port_floatingip_associate_v2

### ISSUE THREAD

**Issue by scat70** [terraform-providers/terraform-provider-openstack#259]
### Terraform Version
Terraform v0.11.3
+ provider.null v1.0.0
+ provider.openstack v1.2.0
+ provider.powerdns v0.1.0
+ provider.template v1.0.0

### Affected Resource(s)
Please list the resources as a list, for example:
- openstack_networking_port_v2

Today one can associate existing floating IPs to a virtual machine, but not to a port. Of course one can associate an existing port to a floating IP when setting up the floating IP. However in my case the floating IPs are fixed assigned to the tenants and should not be changed as they are referenced by firwalls outside OpenStack. Thus recreating a floating IPs when rebuilding resources within the tenant is not an option and it would be really great if an **openstack_networking_port_floatingip_associate_v2** resource could be introduced to realize the assignment in the same way it is realized by **openstack_compute_floatingip_associate_v2**

Regards

**Comment by jtopjian** [comment]
@scat70 Thanks for the suggestion. I understand the use-case and I think a `openstack_networking_floatingip_associate_v2` resource would be useful in certain cases.

One caveat would be that a user could _not_ have both an `openstack_networking_floatingip_v2` and `openstack_networking_floatingip_associate_v2` resource in the same configuration. The reason is because the associate resource would cause an implicit update of the floatingip resource which would not happen until the user performs another `apply`.

For your use-case, you wouldn't run into that issue, but I'll have to think about this some more to see if the above caveat will cause long-term problems.

In theory, this `openstack_networking_floatingip_associate_v2` resource could be modeled off of the `neutron floatingip-associate` command.

Let me think about this one a little. :)

**Comment by scat70** [comment]
@jtopjian Sounds good, thank you very much!

**Comment by jtopjian** [comment]
@scat70 I apologize for the delay. I've submitted #313 which adds this resource. If you're able to test it out ahead of time, let me know what you think. :)

**Comment by scat70** [comment]
@jtopjian Please excuse the late answer. I had a try now and it works well :-) So I can trash my ugly workaround now, many thanks!

**Comment by jtopjian** [comment]
@scat70 That's great news - thanks for the follow-up 😄
