### ISSUE TITLE
NeutronException when getting port from Openstack

### ISSUE THREAD

**Issue by davemac30** [terraform-providers/terraform-provider-openstack#266]
```
$ terraform -v
Terraform v0.11.3
+ provider.openstack v1.2.0
```

The following code:
```hcl
provider "openstack" {}

resource "openstack_networking_network_v2" "default" {
  name = "test"
}

resource "openstack_networking_subnet_v2" "default" {
  network_id = "${openstack_networking_network_v2.default.id}"
  cidr       = "10.2.1.0/24"
}

resource "openstack_networking_port_v2" "default" {
  network_id = "${openstack_networking_network_v2.default.id}"
}

resource "openstack_compute_instance_v2" "default" {
  name        = "default"
  image_name  = "CentOS-7-x86_64-GenericCloud-1708"
  flavor_name = "e1.spc.xsmall"

  network {
    port = "${openstack_networking_port_v2.default.id}"
  }
}
```
Errors like this:
```
* openstack_compute_instance_v2.default: Error trying to get network information from the Network API: Unable to retrieve networks from the Network API: Internal Server Error
```
Looking at the full debug output (see below), at line 3316, it appears that a GET to the following URL is requested like this
```
https://openstack.xxxx.xxxx.com:13696/v2.0/ports?id=29d9db69-3925-41ab-a7fb-5dc0c1f0cad8
```
This seem malformed - the API docs (https://developer.openstack.org/api-ref/network/v2/#show-port-details) indicate that the correct format is /v2.0/ports/{port_id}.

The full debug output at line 426 does have a GET of the port which looks to be in the correct format and does not fail.
```
GET https://openstack.xxxx.xxxx.com:13696/v2.0/ports/29d9db69-3925-41ab-a7fb-5dc0c1f0cad8
```
Full debug output here: https://gist.github.com/davemac30/42faf276b9865d75e17130c1770f1ee9

**Comment by jtopjian** [comment]
@davemac30 Thanks for reporting this and for the detailed analysis 😄 

> This seem malformed - the API docs (https://developer.openstack.org/api-ref/network/v2/#show-port-details) indicate that the correct format is /v2.0/ports/{port_id}.

It's actually doing a "list" by ID:

https://developer.openstack.org/api-ref/network/v2/#list-ports

I can't recall _why_ I implemented a list instead of a GET. There had to have been _some_ edge case I was trying to cover.

Either way, the list _should_ work. This area of code is regularly tested in CI. It's always possible this is a restriction specific to the openstack environment you're using. Is this a public cloud or private/internal cloud? If the latter, do you know what version of OpenStack it's based on? Any customizations being done?

**Comment by davemac30** [comment]
You're right. I hadn't noticed that API when I was looking into the OS docs. I'm on an on-premise cloud which uses contrail for networking. I guess there's some incompleteness in the implementation.

Thanks for looking. I'll close this and raise it internally.

**Comment by jtopjian** [comment]
@davemac30 No problem at all. Let me know if this becomes a blocker for you for using Terraform. I'd be happy to look into changing this List to a Get.
