### ISSUE TITLE
OS_TOKEN is not used, and other auth issues.

### ISSUE THREAD

**Issue by Adrian-Turjak** [terraform-providers/terraform-provider-openstack#271]
Some of the environment variables used by this provider don't match what is considered the standard in OpenStack. The one we've hit is that this provider expects the OS_AUTH_TOKEN variable, while the reference CLI tool in OpenStack expects OS_TOKEN.
https://github.com/terraform-providers/terraform-provider-openstack/blob/master/openstack/provider.go#L75

At the same time, when using token auth, we have to explicitly unset a lot of values because this provider (and potentially gophercloud itself) seem to incorrectly use them when using token auth, unlike the openstack CLI which works fine.

### Expected Behavior
Terraform should be able to auth using the OS_TOKEN variable.
Terraform with token auth should be able to use OS_PROJECT_NAME and OS_PROJECT_DOMAIN_ID 

### Actual Behavior
It fails because it expects OS_AUTH_TOKEN, but also certain other variables that the openstack CLI is fine using, terraform is not.

Once you set OS_AUTH_TOKEN rather than OS_TOKEN, the openstack CLI would work, but not terraform until you remove more variables:
```
* provider.openstack: DomainID may not be provided when authenticating with a TokenID

$ unset OS_PROJECT_DOMAIN_ID
```

The problem is, if you prefer to use OS_PROJECT_NAME rather than OS_PROJECT_ID for readability, you need to provide a domain. 

### Steps to Reproduce
1. Set auth variables
```
export OS_AUTH_URL=https://api.example.com:5000/v3
export OS_IDENTITY_API_VERSION=3
export OS_PROJECT_DOMAIN_ID="default"
export OS_PROJECT_NAME="openstack"
export OS_REGION_NAME="RegionOne"
export OS_AUTH_TYPE="token"
export OS_TOKEN=<somelongfernettoken>
```
2. `terraform plan`
3. observe failure

### Important Factoids
We're hitting this because we use Multi-Factor Authentication in our cloud, and that means password auth is worthless to us since we need to supply a TOTP code with it. We need to auth separately, get a token through the MFA process, save it, and then use that token while it is valid for our actions. Otherwise every command needs the password + totp typed in. We want ideally environment variables and clouds.yaml for tokens to work as expected and consistently because of these reasons across all the OpenStack related CLI tools.

### References
This is tangentially related to: https://github.com/gophercloud/utils/issues/25 (same company)

And this is the change we had to do to find the combination of environment variables that works for both the openstack CLI and terraform with our MFA method:
https://github.com/catalyst-cloud/adjutant-mfa/commit/bb8e7685f7c3083be25a9c5a0e823b755da69227

Ideally we'd like what works with the OpenStack CLI to just work here too in the same way when it comes to auth.

**Comment by Adrian-Turjak** [comment]
The first part of the change, dealing with OS_TOKEN is easy. Replace:
https://github.com/terraform-providers/terraform-provider-openstack/blob/master/openstack/provider.go#L75
With:
```
DefaultFunc: schema.MultiEnvDefaultFunc([]string{
	"OS_TOKEN",
	"OS_AUTH_TOKEN",
}, ""),
```

**Comment by Adrian-Turjak** [comment]
No clue for the rest. I'm not much of a GO dev, and I don't entirely know how this codebase interacts with Gophercloud when it comes to auth.

Although I am curious as to why the provider itself handles environment variables when Gophercloud seems to have that kind of handling also built in. Wouldn't it make sense or be easier for that handling to only be in one place? Is this provider overriding/bypassing that in Gophercloud, but still using Gophercloud for clouds.yaml? I'm curious if there is a good reason behind that, potentially a requirement for terraform provider logic?

Also from what I can tell Gopherclouds's env variable support doesn't support token auth, but initializing it directly with a token does work (which is what this provider does):
https://github.com/gophercloud/gophercloud/blob/master/openstack/auth_env.go#L32
https://github.com/gophercloud/gophercloud/blob/master/openstack/identity/v3/tokens/requests.go#L53

**Comment by jtopjian** [comment]
@Adrian-Turjak Thank you for the report about `OS_AUTH_TOKEN` and the other commentary.

The ability to support an `OS_TOKEN` environment variable is certainly a missing feature and one I would be happy to add support for.

> We're hitting this because we use Multi-Factor Authentication in our cloud, and that means password auth is worthless to us since we need to supply a TOTP code with it. 

Which OpenStack-supported MFA are you using? I'm also happy to add support for that either to here or Gophercloud if more details can be provided. If this is something specific to Catalyst, though, both Gophercloud and this Terraform provider only support OpenStack proper and not modified OpenStack environments (although this Terraform provider is a little lenient when it's easy to do so).

Just to get a clear line of actions here, apart from adding support for the `OS_TOKEN` environment variable, what other pieces are broken?

**Comment by jtopjian** [comment]
@Adrian-Turjak I looped back and re-read everything. I'll try to clarify some areas with some really verbose explanations 😄 

Gophercloud is the API/SDK/library layer for Terraform. Although the same people work on both (primarily myself), they should be thought of as two distinct projects. Gophercloud's design is to provide just enough API support and push everything else onto the apps which consume Gophercloud.

With this in mind, Gophercloud's `AuthOptionsFromEnv` is more of a "take it or leave it" convenience function. It's really only useful for simple OpenStack environments. If that function didn't exist and was submitted today, it would probably be added to the `gophercloud/utils` repo.

One reason `gophercloud/utils` was created was to help bridge the gap between "Gophercloud being too general purpose" and "numerous applications writing the same boilerplate code to interface with Gophercloud". The `clouds.yaml` support is a good example of this. You can see that it has much more robust support for authentication than what's currently in Gophercloud. If someone wanted to revamp some shareable auth functions and submit them to the utils repo, that would be the best course of action here. As it stands, I doubt much work on this topic will go into Gophercloud core.

On the topic of "the Python libraries do this - why doesn't Gophercloud?": that's a common question, especially with authentication. And specifically with authentication, there's a topic here that provides some background info:

https://github.com/gophercloud/gophercloud/issues/252

If you're running into combinations of authentication options that _should_ work but Gophercloud is rejecting them, then there's three possibilities:

1. It's a bug plain and simple.
2. It's something custom being done by the cloud provider.
3. It's something that the Python _client_ libraries are doing as a workaround (perhaps for backwards compatibility or something similar) but the service implementation (in this case the Keystone server itself) would otherwise not consider valid.

The third possibility is what I've commonly run into with auth. I've done _several_ dives into the Keystone code to double-check what Gophercloud is doing is correct and the results have always been affirmative. Gophercloud certainly determines scope information and such in a different way than the Python client, but it's not incorrect.

Of course, there's always the possibility of a bug -- I'm in no way rejecting that.

With this in mind, if you think that you _should_ be able to provide a combination (for example, specifying a Domain ID when authenticating with a Token, we should discuss that over at Gophercloud. It would be helpful (it would certainly save me a few hours of work) if you could point out where in the Keystone server (not client) that allows this (note that this is not a requirement to report a bug - I'm just going on the assumption that you're familiar with the Keystone API and service to immediately know where in Keystone this is allowed.)

(Gophercloud is primarly concerned with what happens in the service code and not the API docs or python client implementations because Gophercloud is not attempting to be a clone of the Python libraries. It's meant to be a small, direct, and correct implementation of the OpenStack API defined by the interaction with the actual OpenStack services)

Let me know if that helps clarify anything.

**Comment by Adrian-Turjak** [comment]
@jtopjian Thanks for looking into this, and the detailed response! And I now have a better understanding of why terraform doesn't use `AuthOptionsFromEnv`.

First off, the MFA as we're currently using it is based on a custom password auth plugin and then reusing the token (see: https://github.com/catalyst-cloud/adjutant-mfa). So no real need to implement that here as it's not exactly an official implementation, but rather a plugin, and in theory the way we are using MFA is still compatible with gophercloud because it's still just 'password' auth technically. 

More official MFA support in Keystone in a useful fashion is coming with this spec: https://github.com/openstack/keystone-specs/blob/master/specs/keystone/rocky/mfa-auth-receipt.rst
And once that is implemented we should consider adding that support in some fashion to gophercloud and such.

As for Keystone auth and scope, that's a complex topic that I keep trying to get my head around and will try and convey as best I can.

The first problem I see with gophercloud is that it isn't entirely using the domain/project values correctly, and this is because those values are honestly weird.

Lets take the examples from the openstackclient:
```
# Who the user is:
OS_USERNAME
OS_USER_ID
# what domain the user is in:
OS_USER_DOMAIN_NAME
OS_USER_DOMAIN_ID

# what the project scope is:
OS_PROJECT_NAME
OS_PROJECT_ID
# what the domain for the project is
OS_PROJECT_DOMAIN_NAME
OS_PROJECT_DOMAIN_ID

# what the domain scope is (mutually exclusive with project scope)
OS_DOMAIN_NAME
OS_DOMAIN_ID
```

The first problem is that terraform and gophercloud is they don't differentiate between all the different domain values and their actual meaning (this is a bug):
https://github.com/jtopjian/terraform-provider-openstack/blob/master/openstack/provider.go#L82-L103

User domain and project domain can be different. A user in a DomainA can scope to a project in DomainB. Then also, a user in DomainA, can _scope_ to DomainC (because domain scope is different to project scope...), hence the `OS_DOMAIN_*` values.

Then as for token auth needing to accept project+domain values, that is because you can rescope a token. A token serves in part to convey scope (authz), but mostly to convey the fact that you have authn, and when you have that, you can change the scope. For the openstackcli when you provide a token, you can also provide a project (and the domain that project is in), so you can rescope to it from the given token. Same with domain scoping. Username and user domain are not needed when you do token auth since the user information is in the token.

For rescoping a token see:
https://developer.openstack.org/api-ref/identity/v3/#token-authentication-with-scoped-authorization

So then that leads me to wonder how the token auth works in gophercloud. When you get a token, are you directly using APIs with said token, or are you getting _another_ token from Keystone which you in turn use for the APIs? If the latter, then you need to support rescoping, if the former, make that clear because that's not how the OpenStackCLI works. The OpenStackClient fetches a new token using the token you've given it, and in that process can rescope to another project. That said, if you do reuse the token directly rather than fetching a new one... that will likely break if the token you're given is unscoped, because an unscoped token can't actually do any real API actions in most of the services.

It's all quite weird, and domains are a concept not everyone (including me) gets right most of the time, so I hope this helps, and I'm more than happy to help you work through this.

What the OpenStack community needs is a spec for what auth looks like in client tools, and cli tools (including what the 'official' envvar names are), so that non-python libraries can implement the same spec we have in the python world through keystoneauth1 and os-client-config.

**Comment by Adrian-Turjak** [comment]
Worth adding, that you only need to specify user/project domains when using user/project names. If you provide user_id, or project_id, then a domain isn't needed because ids are unique across all of Keystone. The domain for those two is only needed when the name is used.

**Comment by jtopjian** [comment]
@Adrian-Turjak Thank you very much for your response 😄 

> in theory the way we are using MFA is still compatible with gophercloud because it's still just 'password' auth technically.

Yes, I browsed through your plugin and came to the same conclusion. I apologize for not doing that beforehand.

> The first problem is that terraform and gophercloud is they don't differentiate between all the different domain values and their actual meaning (this is a bug)

The way Gophercloud determines scope can be found here: https://github.com/gophercloud/gophercloud/blob/master/auth_options.go#L265

My understanding is that Gophercloud has the means to provide all auth configurations defined by the API. Correctly getting all of the pieces in place, however, is the part we're most likely missing.

Gophercloud's auth implementation was done before I started with Gophercloud, though, so there might be some history as to why it's designed the way it is. I have made some modifications to it over the past year, but it seems like it's not entirely complete yet.

> So then that leads me to wonder how the token auth works in gophercloud. 

Gophercloud is expecting the user to provide a scoped token.

> Lets take the examples from the openstackclient:
> snip
> I'm more than happy to help you work through this.
> snip
> What the OpenStack community needs is a spec for what auth looks like in client tools,

Yes. Please. 😄 

What we (Gophercloud team) need is a confident reference of all possible authentication types and the combinations CLI args / env vars to achieve it. 

Once we have that, we can dig through Gophercloud's auth functions and determine if any combination is missing. The best case scenario is that Gophercloud can support all auth types, but there needs to be some layer in between the application (Terraform) and auth request (Gophercloud) to correctly set up the `AuthOptions` struct. 

If you're able to provide a reference to that, would you be able to continue this conversation at https://github.com/gophercloud/gophercloud/issues/252?

**Comment by Adrian-Turjak** [comment]
> The way Gophercloud determines scope can be found here:
> https://github.com/gophercloud/gophercloud/blob/master/auth_options.go#L265

AH! So it does handle scope with domain and project correctly! My bad, it's just terraform that is sourcing and passing along auth variables incorrectly then.

> Gophercloud is expecting the user to provide a scoped token.

That's good to know, and answers that question well, but may be something to reconsider potentially adding support for since ideally the same auth mechanisms that work for openstackclient should just work for terraform. Otherwise people using both on the cli may be hitting weird issues (as evident of this issue).

Not to mention as MFA with that spec gets fully implemented in Keystone, auth with tokens will be more common since you'd auth with MFA first, and reuse your token.

Sooo, I'll close this issue, open a new one here in the terraform provider specific to domain values not being correctly sourced and passed along, and the other parts we can continue in:  Let's move to gophercloud/gophercloud#252
