### ISSUE TITLE
Cascading delete support for Octavia

### ISSUE THREAD

**Issue by jrperritt** [terraform-providers/terraform-provider-openstack#281]
I'm not sure if it's currently possible. From Terraform's perspective, a single resource would be making a `Delete` operation and then that resource's state would be updated. What'd be needed [I think] for cascading delete is to call `resourceLoadBalancerV2Delete` and then, assuming Octavia is being used, to update the entire Terraform state (not just the loadbalancer's, since all the loadbalancer's child resources would be deleted by OpenStack).

After a brief look through Godoc, it seems like [Context.Refresh](https://godoc.org/github.com/hashicorp/terraform/terraform#Context.Refresh) would do this, but I'm not sure how to get a `Context`. There's a `NewContext` function, but it takes a [ContextOpts](https://godoc.org/github.com/hashicorp/terraform/terraform#ContextOpts), which has a bunch of fields. There really should be a simple way to tell Terraform to refresh its current state.

@jtopjian have you had to do something like this before?

**Comment by jtopjian** [comment]
The closest the OpenStack provider has come to this is the `force_destroy` flag in the `openstack_objectstorage_container_v1` resource which will cause all objects to be deleted when the container is deleted. _If_ there were Terraform-managed objects in the container, this would behave similarly to the cascading delete. However, I think `force_destroy` is banking on objects not being managed by Terraform.

I think the main point of difficulty would be having the load balancer resource retrieve (from state) a list of resources that are children of it and then marking them as destroyed so that status is reflected in the state. Doing any type of internal refresh of the state might cause Terraform to flag the resources as needing to be recreated.

I'll ask and see if there's precedence for this type of behavior. In a way, explicitly defining all load balancer resources in a Terraform config is a type of cascading delete, so these two actions might be mutually exclusive.

**Comment by jtopjian** [comment]
Additionally:

> There really should be a simple way to tell Terraform to refresh its current state.

I agree. I first noticed this back in https://github.com/hashicorp/terraform/issues/4118. For OpenStack specifically, this would help with a number of scenarios, for example, the one described in the issue as well as instances and their attached volumes, etc.

However, I'm not sure if it's me getting used to not having this behavior or realizing that it's better design to not have this behavior. By having resources not be able to trigger refreshes of other resources, it encourages a more atomic and explicit design of the infrastructure.

**Comment by jtopjian** [comment]
@jrperritt I'm told that the Azure provider does cascading deletes in some cases and it achieves it by doing a check during the various `Delete` functions to see if the resource still exists. Basically the same kind of 404 check that is currently done during `Read`. However, implementing this kind of action isn't recommended (for all reasons noted above: it's kind of unnatural for the state as well as works against Terraform fully managing the resources).

And in thinking about this more, if the load balancer would support cascading delete, by the time Terraform got to the load balancer during the destroy/delete phase, it would be the only resource left. So that means we have to bypass the `Delete` call of all other resources some how.

One way I can see implementing this is to make a provider-level option of `octavia_enable_cascading_delete` and then for the pools, monitors, members, etc resources check and see if this option is set during `Delete`. If it is, then simply unset the ID and move on. When Terraform got to the load balancer resource, the cascading delete would be triggered.

This could get messy, though. If something prevented the load balancer from being deleted, all resources would still exist but Terraform would only know of the load balancer. Additionally, if something happened during the delete process, the same state mismatch would happen.

With all of that said though, I realize you might have a use case for this that I haven't considered?

**Comment by jtopjian** [comment]
> I guess those other resources would have to look for a config option for the cascading delete too (but where?).

The only place accessible to all would be in the provider block itself:

```hcl
provider "openstack" {
  ...
  octavia_enable_cascading_delete = true
}
```

I'm not opposed to it. My concern is more with the risk of orphaned resources and inconsistent state in the event that the cascade operation failed.

> It's likely environment-related (things like 500s), but it seemed like it would be more efficient and reliable to have Octavia handle all that stuff at once.

I can totally see how Terraform would place stress on the load balancer service by pegging it with requests and polls. I agree having Octavia handle it natively could be more efficient unless, of course, Octavia is doing the same activity internally :)

Here's an idea that's a little out there: what if you created a simple provisioner (which can be bundled as a separate plugin) that only triggered a cascade delete on the load balancer. The provisioner could be triggered when the load balancer was deleted. So Terraform would still do its native destroy on the resources but the provisioner would kick in at the end with a cascade delete as a second measure of deletion.

```hcl
resource "openstack_lbaas_loadbalancer_v2" "lb_1" {
  ...
  provisioner "octavia_cascade_delete" {
    when = "destroy"
  }
}
```

Sharing information between providers and provisioners is even more limited than info between resources, so you'd have to account for authorizing and such within the provisioner.

**Comment by jrperritt** [comment]
> The only place accessible to all would be in the provider block itself:

Agreed, and I don't think that's an appropriate place

> what if you created a simple provisioner (which can be bundled as a separate plugin) that only triggered a cascade delete on the load balancer

That's an interesting idea. I didn't know Terraform offered finalizers like that. I'll look into it.

Thank you for your help on this. In the end, I don't think there's anything to do in the OpenStack provider for this.

**Comment by websi96** [comment]
Isn't the loadbalancer deleted at the end of all it's children? So basically if a child couldn't get deleted, TF should not try to delete it's parent right? This means, the state would be fine.

Here the terraform-provider-openstack uses the neutronloadbalancers delete function of the gophercloud:
[https://github.com/terraform-provider-openstack/terraform-provider-openstack/blob/main/openstack/resource_openstack_lb_loadbalancer_v2.go#L353](https://github.com/terraform-provider-openstack/terraform-provider-openstack/blob/main/openstack/resource_openstack_lb_loadbalancer_v2.go#L353)

The gophercloud would also support a cascade option for the octavia loadbalancer here:
[https://github.com/gophercloud/gophercloud/blob/master/openstack/loadbalancer/v2/loadbalancers/requests.go#L222](https://github.com/gophercloud/gophercloud/blob/master/openstack/loadbalancer/v2/loadbalancers/requests.go#L222)

In my case, I create a Loadbalancer with Terraform and populate it with members by the OpenStack Cloud Controller Manager inside of a k8s cluster. So I would either have cascade available or need to delete the members beforehand..

Wouldn't it be possible to just use the correct octavia delete function of gophercloud?
