### ISSUE TITLE
Update vendor for block storage V3

### ISSUE THREAD

**Issue by flashvoid** [terraform-providers/terraform-provider-openstack#322]
Hi there,

Support for [Cinder V3](https://github.com/gophercloud/gophercloud/pull/415 ) was around for half a year and i would like to use it on terraform. 

I would send a PR but i don't see a documentation on how to upgrade vendor.

**Comment by jtopjian** [comment]
@flashvoid hmm... yeah, you're right. There's basic documentation in the Terraform core [README](https://github.com/hashicorp/terraform#dependencies) -- we should probably add that here.

I've been meaning to do a full Gophercloud update but haven't had a chance. Because of that, I recommend only vendoring the blockstorage/v3 packages (unless other updates are required):

```shell
$ govendor fetch github.com/gophercloud/gophercloud/openstack/blockstorage/v3/...
```

The three dots should be used.

If you do that to a clean checkout of this provider, you'll notice that nothing actually happens. It's not until you begin creating block storage v3 resources that `govendor` will pull in the required libraries.

When committing resources+vendoring, it's recommended to have the vendor update in a separate commit:

```shell
$ git add vendor
$ git commit -m "Updating Gophercloud for blockstorage resource"
```

Let me know if you run into any problems or have any questions.

**Comment by flashvoid** [comment]
@jtopjian i think i figured vendor stuff out. Would you prefer single PR with 2 commits or separate PRs for vendor update and openstack resources?

**Comment by jtopjian** [comment]
@flashvoid A single PR with one resource + vendor works :)

**Comment by flashvoid** [comment]
@jtopjian  ouch, and how do i update `openstack/client.go` to get `NewBlockStorageV3`
i suppose that doing `govendor fetch github.com/gophercloud/gophercloud/openstack/...` not advised?

**Comment by jtopjian** [comment]
@flashvoid Sorry about that, `...` means "current directory and all subdirectories".

If you just want `github.com/gophercloud/gophercloud/openstack/`, you can do:

```shell
$ govendor fetch github.com/gophercloud/gophercloud/openstack/
```

However, one thing to note is that the `./openstack` directory will be updated in this PR: https://github.com/terraform-providers/terraform-provider-openstack/pull/320

I'll see if I can get this reviewed tomorrow so we don't run into a merge conflict :)

**Comment by swapnilgm** [comment]
Why don't we use go dependency management tool like [dep](https://github.com/golang/dep)?

**Comment by jtopjian** [comment]
@swapnilgm That's more of an upstream Terraform decision. The individual provider plugins follow the same toolchain as core :)

**Comment by jtopjian** [comment]
@flashvoid Would you consider this issue closable or was there more you wanted to do with blockstorage v3?

**Comment by flashvoid** [comment]
@jtopjian all good, thanks.

**Comment by jtopjian** [comment]
@flashvoid Sounds good -- thank you for implementing these resources :)
