### ISSUE TITLE
Keypair resource should reuse existing key instead of failing

### ISSUE THREAD

**Issue by megakoresh** [terraform-providers/terraform-provider-openstack#334]
If I have multiple infrastructures or tenants (or I am using IDM-managed SSH keys), chances are I will use the same key for accessing different terraform-deployed infrastructures. However if I include key resource declaration into terraform config, it will work once, but for any future infrastructure it will fail due to key already being defined, since the key is account-wide. 

I would like to avoid having to rely on Openstack GUI to add SSH keys, so it would be helpful if terraform checked if the key with the name I have given already exists and use existing one if possible. After all keypairs are not infrastructure-specific, but user-specific so the same conventions as for infrastructures shouldn't necessarily apply to them.

### Terraform Version
0.11.7

### Affected Resource(s)
- openstack_compute_keypair_v2

### Terraform Configuration Files
```hcl
resource "openstack_compute_keypair_v2" "keypair" {
  name       = "${var.keypair_name}"
  public_key = "ssh-rsa blablabla"
}
```

### Debug Output
N/A

### Expected Behavior
State should be updated with existing key, and the existing key should be used, if its present.

### Actual Behavior
Terraform tries to provision the key again and fails due to name collision.

### Steps to Reproduce
1. Define public key resource to be added to your account via terraform
2. Create new infrastructure (that would have a separate statefile)
3. Define the same public key resource to the new infrastructure
4. Watch as it bursts into flames since you are using the same openstack account

**Comment by megakoresh** [comment]
Worth noting, by the way, that the current failure in this case is nothing more than ugliness. It will still provision all the infra correctly with the existing key, and spit out the name collision error at the end. And it will not update the statefile properly meaning that it will always fail this way which is ugly and also breaks any automation built on top of terraform.

**Comment by jtopjian** [comment]
> If you're familiar with Puppet or any other configuration management system, think of this as similar: you can't define the same resource in multiple places.

Just to clarify - the issue you're running into isn't _exactly_ like a unique constraint in a configuration management system. The problem is that a unique key name already exists in OpenStack and so it's not possible to define it in multiple Terraform configurations/states. If you want to use Terraform to manage the keypair, you'll need to use a separate state to manage it by itself (or with other unique resources like security groups). Your other Terraform configurations will omit further redefinitions of `openstack_compute_keypair_v2` resources.

**Comment by megakoresh** [comment]
@jtopjian I do have questions. What is a common configuration pattern in Terraform? Separate state file for ssh keys? This would not be feasable in any production environment of even moderate scale, let alone large enterprise environments.

Even for testing I have 3 tenants, each with their own key, and there are 12 separate infrastructures across those tenants. It would be an unmanageable mess if I used separate keys for each infrastructure, (and it wouldn't be possible if I started using IDM managed keys). Also people ususally work on devops and software development in teams these days, and having a separate statefile for every person who participates in a project just because of a keypair (because it must have the same name for everyone) seems excessively complicated.

Way I see it, if keypair resource cannot be made an exception from the rules, due to it having a completely different lifecycle to the rest of resources, it should just be removed. I don't see it as having any practical use under these constraints.

A compromise might be adding a "ignore_errors" option to the resource, so that it doesnt throw an error if it couldn't add a resource. The key is referenced by name elsewhere, so merely ignoring the resource when it exists is enough, no need to take over it's lifecycle, since like I said: everything still works, it just produces unnecessary error.

**Comment by jtopjian** [comment]
> What is a common configuration pattern in Terraform?

This is largely a matter of taste and what best fits the situation. The solution is _very_ specific to each user/organization using Terraform.

> Separate state file for ssh keys? This would not be feasable in any production environment of even moderate scale, let alone large enterprise environments.

A common pattern is to do something like this:

```
.
├── base
│   └── main.tf
├── db
│   └── main.tf
└── web
    └── main.tf
```

`base/main.tf` would contain the keypair resources. Then `web/main.tf` would have something like this:

```hcl
resource "openstack_compute_instance_v2" "basic" {
  ...
  key_pair   = "hard-coded-name-or-variable-reference"
  ...
}
```

Another option is to use the meta-like [Terraform data source](https://www.terraform.io/docs/providers/terraform/d/remote_state.html) to reference information in other state files.

> Way I see it, if keypair resource cannot be made an exception from the rules, due to it having a completely different lifecycle to the rest of resources, it should just be removed. I don't see it as having any practical use under these constraints.

The same can be said about security groups and every other resource that has a unique constraint on the name. These resources have very valid purposes. They aren't invalid just because they aren't fitting in to your workflow.  😄 

> A compromise might be adding a "ignore_errors" option to the resource, so that it doesnt throw an error if it couldn't add a resource. The key is referenced by name elsewhere, so merely ignoring the resource when it exists is enough, no need to take over it's lifecycle, since like I said: everything still works, it just produces unnecessary error.

That can lead to other problems, though. This method is making multiple sources the "owner" of the resource. What happens when one owner wants to delete the keypair but then another owner recreates it?

> Also people usually work on devops and software development in teams these days, and having a separate statefile for every person who participates in a project just because of a keypair (because it must have the same name for everyone) seems excessively complicated.

This is true. At the same time, OpenStack (and other cloud providers) only allow creating an instance with _one_ key pair. If you have multiple people who need to access an instance, then you need to add additional keys after the instance has launched (using some provisioning tool like Puppet or Ansible). 

It sounds like you have a greater need for key management than what can be achieved with the `openstack_compute_keypair_v2` resource alone. If you find it difficult to manage keys with Terraform alone, please don't try to shoe-horn your workflow to fit Terraform. At the same time, I know it's not helpful, but I can't really give a confident answer about how to proceed because then I would be dictating how to use Terraform to match your workflows which I don't want to do 😄 

It might be worthwhile to search Github for various repositories (searching for the generic word "terraform" and limiting by language "hcl" like [this](https://github.com/search?q=language%3Ahcl+terraform) will yield a lot of results to look at) as well as browsing the mailing list archives (the topic of large-scale management of Terraform resources comes up often) might be very beneficial.

**Comment by megakoresh** [comment]
I don't see any correlation between security groups and private keys. One is project-specific, other is user-specific. There is no other resource that Terraform manages in Openstack which spans multiple projects (aside from shared networks, but it still has an owner project).

Seems like this use case is not supported. We will have to manually add ssh keys to our accounts before using Terraform.
