### ISSUE TITLE
openstack_compute_instance_v2 access_ip_v6 returns addresses in literal syntax

### ISSUE THREAD

**Issue by Lasering** [terraform-providers/terraform-provider-openstack#337]
### Terraform Version
```
Terraform v0.11.7
+ provider.openstack v1.5.0
```
### Affected Resource(s)
- openstack_compute_instance_v2
- openstack_dns_recordset_v2

### Terraform Configuration Files
```hcl
resource "openstack_compute_instance_v2" "servers" {
  count = "${var.number-of-servers}"

  name        = "server${count.index}-${var.suffix}"
  flavor_name = "${var.flavor-name}"
  image_name  = "${var.image-name}"

  key_pair        = "${local.keypair}"
  security_groups = ["${openstack_networking_secgroup_v2.consul.name}"]
}

resource "openstack_dns_recordset_v2" "server-ipv6" {
  zone_id = "${data.openstack_dns_zone_v2.default.id}"
  name    = "${local.address}."
  ttl     = 1
  type    = "AAAA"
  records = ["${openstack_compute_instance_v2.servers.*.access_ip_v6}"]
}
```
### Actual Behavior
`openstack_dns_recordset_v2.server-ipv6: Error creating OpenStack DNS record set: Invalid request due to incorrect syntax or missing required parameters.`

### Expected Behavior
Either:

  1. The field `access_ip_v6` of `openstack_compute_instance_v2.servers` should return the IPv6 addresses without any brackets, aka, not in literal syntax.
  2. `openstack_dns_recordset_v2` should accept the value returned by `${openstack_compute_instance_v2.servers.*.access_ip_v6}`

### Important Factoids
This hack solves the problem while its not fixed:
```hcl
resource "openstack_dns_recordset_v2" "server-ipv6" {
  zone_id = "${data.openstack_dns_zone_v2.default.id}"
  name    = "${local.address}."
  ttl     = 1
  type    = "AAAA"

  # Records must be an array of IPv6 address without brackets. So this is valid: ["8afe:affb:9d95:d381:40c:7d10:c714:339e", "e163:648f:7797:3548:9827:7799:cbd3:e5fa"]
  # However this is not: ["[8afe:affb:9d95:d381:40c:7d10:c714:339e]", "[e163:648f:7797:3548:9827:7799:cbd3:e5fa]"]
  # Unfortunately openstack_compute_instance_v2.servers.*.access_ip_v6 returns an array of IPv6 addresses in literal syntax
  # aka with the square brackets. To overcome this issue (and because terraform has no function to map over a list)
  # we had to resort to this ugly hack which creates a string from the array, replaces all the square brackets with the
  # empty string and then splits it back to an array.
  records = ["${split(",", replace(join(",", openstack_compute_instance_v2.servers.*.access_ip_v6), "/\\[|\\]/", ""))}"]
}
```

**Comment by jtopjian** [comment]
@Lasering Thanks for opening this.

> The field access_ip_v6 of openstack_compute_instance_v2.servers should return the IPv6 addresses without any brackets, aka, not in literal syntax.

The brackets are intentional and are the expected format. This is to match how IPv6 is handled elsewhere in Terraform. I understand that when setting a DNS record (and some other random areas), the brackets are an inconvenience, but at the same time, if we remove the brackets, then there will be other areas that need the brackets to be added!

This is also more of a historical behavior that would be too intrusive to change at this point. For example, years ago the Terraform SSH communicator required the brackets for IPv6. I believe the SSH communicator will now add brackets if needed, but there was a long period of time when this support wasn't available.

> openstack_dns_recordset_v2 should accept the value returned by ${openstack_compute_instance_v2.servers.*.access_ip_v6}

I think this is a valid request, but I'll have to think about it a little.

One one hand I agree that it would be very user-friendly and reduce the amount of variable modifications. On the other hand, I'm not a fan of having resources mutate input and appear as if magic things are happening. 

I'm leaning more on implementing this, but let me think about it a little.

Side note: you no longer have to escape the brackets in the `replace` function. The following works: `"/[][]/"`. It's not a full solution, but it helps reduce the ugliness slightly 😄 

Please let me know if you have any questions.

**Comment by Lasering** [comment]
Have you given some though about option 2?
> openstack_dns_recordset_v2 should accept the value returned by ${openstack_compute_instance_v2.servers.*.access_ip_v6}

**Comment by jtopjian** [comment]
@Lasering I apologize for the delay. I've submitted #443 which enables the `openstack_dns_recordset_v2` resource to strip the brackets from the addresses.

If you're able to do a custom compile of the code to test and provide feedback, that would be much appreciated. But I've also tested this myself and can confirm it works.

**Comment by Lasering** [comment]
Just tested it, works correctly :tada:
