### ISSUE TITLE
Feature Request: Data source for snapshots

### ISSUE THREAD

**Issue by triazo** [terraform-providers/terraform-provider-openstack#354]
It would be useful to be able to use snapshots as a data source, similar to images are handled. Right now there does not appear to be a way to obtain a snapshot id. Our workflow will have us automatically creating new snapshots using packer and using the id of the new snapshot in a volume created using the openstack_blockstorage_volume_v2, using the snapshot as a base. When using the rbd driver, this creates a copy on write clone that is far more efficient. However as of writing now there appears to be no way to obtain the required snapshot id in terraform.

Here's how I imagine it could look:
```hcl
data "openstack_blockstorage_snapshot_v2" "snapshot" {
  name = "shiny-new-snapshot"
  most_recent = true

  properties {
    key = "value"
  }
}
```

Note that openstack allows you to have multiple snapshots with the same name, so some of the ideas from the image data source may apply.

It looks like gophercloud has some code for dealing with snapshots already: [https://github.com/gophercloud/gophercloud/tree/master/openstack/blockstorage/v3/snapshots](https://github.com/gophercloud/gophercloud/tree/master/openstack/blockstorage/v3/snapshots)

**Comment by jtopjian** [comment]
@triazo This all sounds good to me. We don't have snapshot _resources_ since the action of creating a snapshot doesn't mix very well with Terraform, but a data source is definitely applicable.

We should probably have two data sources though: one for block storage v2 and one for v3. They'll be identical except for the client used.

Gophercloud's snapshot support should be capable of handling all of this.

If you're keen to write the data sources (or even 1 of them), I would be happy to review it. Otherwise I will try to find some time in the near future to do this.

**Comment by jtopjian** [comment]
This has been added in #448 and will be available in the next release.
