### ISSUE TITLE
Terraform is not tolarable with volume Size difference

### ISSUE THREAD

**Issue by kylixtan** [terraform-providers/terraform-provider-openstack#37]
when i attached a 500G volume to an openstack instance. the openstack will create a 504G volume and attach it to the instance.

but terraform does not understand this mismatch, it just will destory this 504G disk and create a new one during next apply action.

**Comment by fatmcgav** [comment]
@kylixtan My initial thought is that Terraform is exhibiting _correct_ behaviour, in as much as you are explicitly asking for a 500G volume, however Openstack is telling Terraform it's provisioned a 504G volume. Therefore Terraform is attempting to correct the incorrectly provisioned volume. 

What happens if you request a 504G volume? Is Openstack always adding to the requested volume size? As that sounds like erroneous Openstack behaviour to me... 

HTH

**Comment by DSpeichert** [comment]
@kylixtan What is the OpenStack version and Cinder backend driver in use?

It could be that backend storage driver is modifying (for whatever reason) the size and creating a different volume (due to its internal reasons).

**Comment by jtopjian** [comment]
Due to the inactivity of this issue, I am going to close it. I am happy to re-open and investigate if this is still a problem with the current release and/or further details of this are provided.
