### ISSUE TITLE
New property forces resource recreation

### ISSUE THREAD

**Issue by xocasdashdash** [terraform-providers/terraform-provider-openstack#391]
### Affected Resource(s)
openstack_compute_floatingip_associate_v2

### Terraform Configuration Files
Does not apply
### Debug Output
Does not apply
### Expected Behavior
Updated to v1.6.0. Everything should be ok.

### Actual Behavior
This PR https://github.com/terraform-providers/terraform-provider-openstack/pull/310 added an option to wait until the IP is available. Because it forces a new resource it's making terraform delete and recreate the resources even when it's not needed. 

### Steps to Reproduce
run terraform plan

I don't know if this change should force a new resource, if it's necessary I think it should be noted in the CHANGELOG.md document (maybe going forward this could be a policy? )

**Comment by jtopjian** [comment]
@xocasdashdash Can you provide the Terraform configuration to reproduce this test case?

**Comment by xocasdashdash** [comment]
@jtopjian well, I think the important part is deciding if this should force or not a new resource. It's just a floating ip association to an instance so any working example should trigger this behaviour.

I'm not sure we can call it a bug because maybe it has to be like this because reasons it's just that I don't see the reason behind it so I'm proposing to maybe undo that change.

**Comment by jtopjian** [comment]
> I think the important part is deciding if this should force or not a new resource

This might be a little confusing but I'll try to explain:

The `openstack_compute_floatingip_associate_v2` really only has two inputs: the floating IP and the instance ID. If you were to change one of those, then the floating IP would be disassociated from the instance and a new association would be made. This is the exact same behavior as if the resource was destroyed and recreated.

Because of this similarity, the code for the [resource itself](https://github.com/terraform-providers/terraform-provider-openstack/blob/master/openstack/resource_openstack_compute_floatingip_associate_v2.go) has no "update" phase. Therefore all fields must be `ForceNew`.

> so any working example should trigger this behaviour

This is the problem - I can't reproduce this behavior. 

Whether I use `wait_until_associated` or not, the resource does not trigger a rebuild behavior.

Unless,

> Updated to v1.6.0. Everything should be ok.

So what you're saying is that you updated to the latest version of Terraform and upon applying a configuration/state which was made prior to 1.6.0, the new version of this provider triggered a rebuild of this resource?

If this is true, then this certainly was not the intended behavior for users who updated. We can get a bug fix out for this.

**Comment by jtopjian** [comment]
Actually, I just verified this behavior by switching between two different releases.

So this was not intended behavior and we'll get a fix out for this. If it was, then it would have definitely been note in the CHANGELOG.

Thank you for reporting it.

**Comment by xocasdashdash** [comment]
Thanks! 
Yeah, that's exactly what was happening. Here's the line that triggers the rebuild:
 https://github.com/terraform-providers/terraform-provider-openstack/blob/master/openstack/resource_openstack_compute_floatingip_associate_v2.go#L61

reading the associated test case, if we just change the "recreation" behaviour to avoid forcing a new resource everything should work as is. I can't think of some usage where this would be the expected use.

**Comment by jtopjian** [comment]
> Here's the line that triggers the rebuild

Right - that's setting `ForceNew`, but what is actually triggering the rebuild for users who are updating is this:

https://github.com/terraform-providers/terraform-provider-openstack/blob/master/openstack/resource_openstack_compute_floatingip_associate_v2.go#L59

The `Default` value is having Terraform write the new property to the state file and thus triggering a rebuild. If a `Default` value was never specified, this would behavior would not be happening. Lesson learned on my part.

**Comment by xocasdashdash** [comment]
ohhh, i see, so both lines need to change then right? 
Remove the default to avoid the change detection and don't force new if the value changes. Am I correct?

**Comment by jtopjian** [comment]
No, only the `Default` line needs removed.

`ForceNew` must be set or else the following error will occur:

```
* resource openstack_compute_floatingip_associate_v2: No Update defined, must set ForceNew on: []string{"wait_until_associated"}
```

In order to avoid that, we must define an `Update` function in the resource. But that won't make sense because none of the properties in this resource are actually able to be updated.

I'll have a patch ready shortly.

**Comment by jtopjian** [comment]
@xocasdashdash Version 1.8.0 was just released which should fix this issue. Please let me know if you're still encountering problems, though.

Thank you fore reporting this!
