### ISSUE TITLE
Instances rebuilding

### ISSUE THREAD

**Issue by rruu** [terraform-providers/terraform-provider-openstack#397]
### Terraform Version
terraform -v
Terraform v0.11.7
+ provider.openstack v1.7.0

### Affected Resource(s)
Please list the resources as a list, for example:
- opc_instance

### Terraform Configuration Files
https://gist.github.com/rruu/d1477793c5770d4255d727aad9d06346

### Debug Output
1. Create first - https://gist.github.com/rruu/05d3c6017dc1f5b0053cf425eb7b543b
2. Just add new instance - https://gist.github.com/rruu/227b5f8751124ffd76bbc1318f29e11c

### Expected Behavior
Add new instances

### Actual Behavior
Destroy first instance and create new.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `uncomment app02 section (add openstack_compute_instance)` 
2. `terraform apply`

**Comment by jtopjian** [comment]
@rruu I don't think your problem is related to adding a second instance. You should be able to reproduce this problem by running `terraform apply` twice with out modifications to your configuration.

I believe the problem is that you are specifying an `image_id` when you are booting from a volume.

When you are booting from a volume and you are using the image as the source, do not set `image_id`. Instead, set the `block_device.uuid` to the image ID.

You can use the following example as a template:

https://www.terraform.io/docs/providers/openstack/r/compute_instance_v2.html#boot-from-volume

Please let me know if that helps.

**Comment by rruu** [comment]
Thank you!
Comment line ```image_id=``` helps. 
Gone to read docs.  )

**Comment by rruu** [comment]
I think this issue can be closed.
