### ISSUE TITLE
Override timeouts for LBv2 creates

### ISSUE THREAD

**Issue by jamiehannaford** [terraform-providers/terraform-provider-openstack#41]
We've seen a few instances in our deployments of LBs being created, but not transitioning from `PENDING_CREATE` to `ACTIVE`. The current behaviour is to [wait](https://github.com/terraform-providers/terraform-provider-openstack/blob/be7c7c995a0ef35bd0ec1dfbdc4d75a10dd2dd0b/openstack/resource_openstack_lb_loadbalancer_v2.go#L24) up to 20 minutes, which is suboptimal - we'd like to fail quicker. I see that the timeouts are defined globally. Can we add the ability for these to be overrided in the `resource` blocks? I can submit a PR if so, just wanted to check with folks first for the best solution.

**Comment by jtopjian** [comment]
Hi Jamie,

A few notes about this, which may or may not help. I've had LB timeouts on my mind since doing #32 and have been thinking of how to clean it up, so your question has prompted me to lay things out :)

1. Similar to #31, I apologize for asking this but I just don't want to assume: you know timeouts can be [overrided within the resource declaration](https://www.terraform.io/docs/configuration/resources.html#timeouts)?

2. The timeout schema is core to Terraform. There is support for values during C, R, U, and D. You can't add arbitrary timeout values, unfortunately. I'd be very hesitant to add either provider-level or resource-level schema options (ex: adding the following to the pool resource: `lb_refresh_timeout`). I'm not against it, the idea just initially feels wrong. Similarly, adding static values for timeouts has historically been a problem. That's why the whole `timeout` schema was introduced :)

2. I take full responsibility for the LB resources having such high timeouts by default. This was due to my testing with Octavia where it takes forever to transition to `ACTIVE`. I would be totally fine lowering the default timeouts and putting responsibility on the user to increase the timeouts when they run into this situation.

3. The LB resources are a bit unique in that they depend on other LB-type resources. During each of these checks, the resource's action (CRUD) timeout is used for _each_ call within the action. So a default timeout of 20m will allot each call 20m, possibly taking the entire `Create` action 40,60,80 minutes in total. Only those who have poked in the code understand why this is. Users who are just using Terraform are oblivious to this (rightfully so). One idea I had was to use a running timeout by calculating the amount of time it took a certain call to run and then deducting it from the default timeout. Then when the next call runs, it uses that reduced timeout instead of a brand-new 20m. By doing this, the entire `Create` action should only take 20m.

Let me know if any of that has helped or not.

**Comment by jamiehannaford** [comment]
@jtopjian Thanks for the great response. I'm still learning Terraform and didn't know you could scope timeouts to the resource block! 😄

**Comment by jamiehannaford** [comment]
@jtopjian Is it okay if we lower the [default timeouts](https://github.com/terraform-providers/terraform-provider-openstack/blob/master/openstack/resource_openstack_lb_loadbalancer_v2.go#L24-L26)? How do you feel about 10m for creates + updates, 5m for deletes? Or maybe lower. I can submit a PR if it's fine with you.

**Comment by jtopjian** [comment]
@jamiehannaford Sure, that's fine with me. I don't think we should go lower than 5 minutes, though.
