### ISSUE TITLE
Compute V2: cloud-side resize verifying

### ISSUE THREAD

**Issue by ozerovandrei** [terraform-providers/terraform-provider-openstack#420]
Greetings.

Right now `terraform-provider-openstack` always waits for 10 seconds to get the `VERIFY_RESIZE` status of a Compute instance and then sends verify request: [resource_openstack_compute_instance_v2.go#L810](https://github.com/terraform-providers/terraform-provider-openstack/blob/master/openstack/resource_openstack_compute_instance_v2.go#L810)

This behavior doesn't work well in cases where OpenStack cloud provider automatically sets the `ACTIVE` state for the Compute instance.
Cloud provider can do that by setting the [resize_confirm_window](https://docs.openstack.org/nova/rocky/configuration/config.html#DEFAULT.resize_confirm_window) value to some integer. In that case Compute service will automatically confirm resize of the instance after configured interval.
Therewith `terraform-provider-openstack` will throw an error and won't complete the resize operation: [resource_openstack_compute_instance_v2.go#L812](https://github.com/terraform-providers/terraform-provider-openstack/blob/master/openstack/resource_openstack_compute_instance_v2.go#L812).

I think of two ways of how to deal with it:
- allow to configure `resource.StateChangeConf.Delay` by some env variables instead of using hardcoded values;
- don't interrupt resize action on verify errors, just warn in log (or even quietly continue if instance is already in `ACTIVE` state).

@jtopjian thoughts?

References:
https://docs.openstack.org/nova/rocky/user/resize.html
https://developer.openstack.org/api-ref/compute/#resize-server-resize-action

**Comment by jtopjian** [comment]
Good question... I'm not very familiar with resizing.

Option 1 might cause issues depending on what the cloud provider has set the resize window to. No matter what value the user sets, in some situations Nova might always confirm first.

Instead of an environment variable to set the delay, what about an argument+env var that skips/ignores resize errors? Maybe we could model this as a [`vendor_option`](https://github.com/terraform-providers/terraform-provider-openstack/blob/e9fe36a257561b7b0a7e29ff409e504c8305facf/openstack/resource_openstack_networking_router_v2.go#L111-L126) of `ignore_resize_confirmation` or something like that?

**Comment by ozerovandrei** [comment]
@jtopjian sounds great.

I will create a PR with `ignore_resize_confirmation` option then.

**Comment by ozerovandrei** [comment]
Implemented in #422
