### ISSUE TITLE
Support l7policy and l7rule resources for LBaaS (load balancer)

### ISSUE THREAD

**Issue by kayrus** [terraform-providers/terraform-provider-openstack#503]
It would be nice to support l7policy and l7rule resources for LBaaS API in Terraform

### Terraform Version
0.11.10

### Affected Resource(s)
* openstack_lb_l7policy_v2
* openstack_lb_l7rule_v2

### Terraform Configuration Files
N/A

### Debug Output
N/A

### Panic Output
N/A

### Expected Behavior
I can create l7policy and l7rule resources via terraform.

### Actual Behavior
I can't create l7policy and l7rule resources via terraform.

### Steps to Reproduce
1. Try to create l7policy and l7rule resources using Terraform. 
2. Be disappointed

### Important Factoids
There are gophercloud dependencies:
* https://github.com/gophercloud/gophercloud/issues/1332
* https://github.com/gophercloud/gophercloud/issues/1333
* https://github.com/gophercloud/gophercloud/issues/1348

### References
* WIP is happening here: https://github.com/kayrus/terraform-provider-openstack/commit/1c543e8a8198fba8233cc89a9bf1327f04ab6c46

**Comment by kayrus** [comment]
Existing `openstack_lb_*` resources use `gophercloud/openstack/networking/v2/extensions/lbaas_v2`. New resources will use `gophercloud/openstack/loadbalancer/v2`.
@jtopjian, what do you suggest?
* Keep it as is?
* Create new v2.1 resource version?
* Replace existing dependency with the `lb/v2`?
* Add a logic into existing resources and dynamically switch between `extensions/lbaas_v2` and `lb/v2`?

**Comment by jtopjian** [comment]
At the moment, users can take advantage of using Octavia with the existing lb resources by setting `use_octavia` to `true` in the `provider` block:

* https://github.com/terraform-providers/terraform-provider-openstack/blob/master/openstack/lb_v2_shared.go#L18-L25
* https://github.com/terraform-providers/terraform-provider-openstack/search?q=chooseLBV2Client&unscoped_q=chooseLBV2Client

This works because everything in `gophercloud/openstack/loadbalancer/v2` (Octavia) is also in `gophercloud/openstack/networking/v2/extensions/lbaas_v2` - the API URLs and methods are the exact same.

However, as Octavia continues to develop and diverge from Neutron LBaaS, this won't be a satisfactory solution. IMO, this is still a long ways off, though. But, when it happens, it would be best to create a new suite of resources, probably something like `openstack_lbaas_*`. There will be some confusion for sure, but architecturally it's the best way to go - this allows the `openstack_lbaas_*` resources to not have to deal with any legacy aspects of the Neutron LBaaS APIs.

Until that time, though, I recommend continuing to implement the Neutron LBaaS API in the existing `openstack_lb_*_v2` resources. This way we don't have two sets of resources that are completely identical. Waiting until there is a good reason will provide a better explanation of when and why to use the different sets of resources.

With all of that said, I'm open to comments and feedback on this idea.

/cc @ozerovandrei

**Comment by jtopjian** [comment]
Ah, and I now see that the L7 stuff isn't in Gophercloud's `openstack/networking/v2/extensions...`. I thought it was.

Step 1 would be to determine if it really is only in Octavia (I can't remember off the top of my head). Step 2 is to determine if this is enough to make a new set of resources... I'll have to think about that.

**Comment by jtopjian** [comment]
> According to what I see, current gophercloud/openstack/loadbalancer/v2 implementation represents neutron-lbaas v2 extension:

This is correct. The initial loadbalancer commit was done earlier this year and it was, literally, a copy and paste and sed of Neutron LBaaS v2.

> These resources are not identical. There are already new types of fields introduced for Octavia, but not reflected in gophercloud.

No doubt. Gophercloud features are most always added when someone comes across a feature they need. This is totally fine, but means that the API implementations have holes in them.

**Comment by jtopjian** [comment]
These were implemented in #522 and #527.

**Comment by jtopjian** [comment]
@kayrus Thank you very much for your hard work getting these implemented and the effort that went into preparing them to get added.

**Comment by kayrus** [comment]
I also appreciate your help. I didnt expect so many pitfalls in dependencies and I'm glad that it is finally merged. Merry Christmas ;)
