### ISSUE TITLE
Need option to specify tenant id in openstack_compute_instance

### ISSUE THREAD

**Issue by dshailen** [terraform-providers/terraform-provider-openstack#517]
In a multi tenant deployment use case we need an option to map a specific tenant id to a compute instance. Currently such an option is not available in openstack_compute_instance_v2 resource and the instance gets implicitly assigned to the tenant specified in the provider.

### Terraform Version
Terraform v0.11.10
+ provider.openstack v1.12.0

### Affected Resource(s)
- openstack_compute_instance_v2

**Comment by jtopjian** [comment]
@dshailen Unless I'm mistaken, this is not possible to do with the API which creates servers: https://developer.openstack.org/api-ref/compute/?expanded=create-server-detail#create-server

This might be possible to do with the OpenStack command-line client, but this is most likely due to rescoping to another project on-the-fly before the actual Compute API request is made. I could be wrong about that, and if you're aware of how to do this with the API, please let me know.

But if it truly isn't possible with the API call, this isn't a feature we'll be able to add to this provider. The way Terraform authenticates with the provider and then executes a resource doesn't allow a window for this rescoping to happen (at least not sanely).

Other OpenStack projects, such as Neutron / Networking allow an admin to specify a project ID in order to create resources in the manner you're describing.

Please let me know if you have any questions.

**Comment by mandeepdhami** [comment]
In Openstack compute API, the tenant ID is encoded in the service URI and an token has to be retrieved from keystone for that tenant specific action.

So, if I want to specify tenant_id in the resource definition, I need to make an additional GET request to "http://<server-ip>:5000/v3/auth/tokens" to use the token and nova endpoint in that response for doing the specific resource action. That is, if I want to create a VM in tenant "X" as user "Y", then I first need to do a get with data like:
{ "auth": {
    "identity": {
      "methods": ["password"],
      "password": {
        "user": {
          "name": "Y",
          "domain": { "id": "default" },
          "password": "password"
        }
      }
    },
    "scope": {
      "project": {
        "name": "X",
        "domain": { "id": "default" }
      }
    }
  }
}

The response will contain auth token in "X-Subject-Token" and the "endpoints" list member with name "nova" will be the URI to use for doing the POST on /servers to create the VM.

See: https://docs.openstack.org/keystone/pike/api_curl_examples.html for an example. Hope this helps!

**Comment by jtopjian** [comment]
@mandeepdhami Right - this is what I was describing in my last comment: it's not possible to do this kind of on-the-fly rescoping in Terraform. In order for this pattern to work in Terraform, you would have to create a separate `provider` block with the project you want to scope to. Think of the `provider` block as doing the GET to `/v3/auth/tokens` as you've laid out.

But again, some services like Neutron provide the ability to create a resource on behalf of another tenant without the need to rescope. I haven't seen this in Nova / Compute.

**Comment by dshailen** [comment]
@jtopjian Thanks for clarifying this. Closing the issue now.
