### ISSUE TITLE
FEATURE: ressource openstack_networking_port_v2: Define security groups via name

### ISSUE THREAD

**Issue by buec011** [terraform-providers/terraform-provider-openstack#553]
### Terraform Version
Terraform v0.11.11
provider.openstack: version = "~> 1.13"

### Affected Resource(s)
Please list the resources as a list, for example:
openstack_networking_port_v2

### Terraform Configuration Files
```hcl
resource openstack_networking_port_v2 port {
   network_id="48a2e109-02a9-4a8e-aa4b-ccc4018f02e5"
   security_groups=["default"]
}

output port_id {
   value="${openstack_networking_port_v2.port.id}"
}
```

### Expected Behavior
It should be possible to define security groups via name, similar to openstack_compute_instance_v2.

### Actual Behavior
What actually happened?
The key is not known:

Error: openstack_networking_port_v2.port: : invalid or unknown key: security_groups

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

**Comment by jtopjian** [comment]
@buec011 Thank you for submitting this.

> It should be possible to define security groups via name, similar to openstack_compute_instance_v2

Being able to specify security groups by name rather than ID has become problematic over time. I believe `openstack_compute_instance_v2` is the only resource that will allow this kind of behavior. For everything else, we have standardized on using UUIDs.

It's possible to do a name-to-uuid conversion using the `openstack_networking_secgroup_v2` data source: https://www.terraform.io/docs/providers/openstack/d/networking_secgroup_v2.html

By using it, you can do something like this:

```hcl
data "openstack_networking_secgroup_v2" "secgroup" {
  name = "tf_test_secgroup"
}

resource openstack_networking_port_v2 port {
   network_id="48a2e109-02a9-4a8e-aa4b-ccc4018f02e5"
   security_groups_ids=["${data.openstack_networkign_secgroup_v2.secgroup.id"]
}
```

I'm going to close this issue, but please let me know if you'd like to discuss this further.

**Comment by buec011** [comment]
Maybe I need to describe my use case further: We have a list of security groups in a tfvars file. During the lifecycle of an instance we extend the list or remove some of the security groups.

For one security group your solution is sufficient, but how to deal with a (dynamic) list of security groups?
Any idea?
