### ISSUE TITLE
Networking V2: Mark network tags as computed

### ISSUE THREAD

**Issue by kayrus** [terraform-providers/terraform-provider-openstack#620]
In our openstack environment tags are added automatically by a backend network driver. When tags are not explicitly defined in terraform manifests, terraform tries to remove them. As a workaround I use:

```hcl
  lifecycle {
    ignore_changes = ["tags"]
  }
```

I suggest to add a `Computed: true` for tags attribute.

### Affected Resource(s)
Please list the resources as a list, for example:
- openstack_networking_network_v2
- openstack_networking_subnet_v2
- openstack_networking_subnetpool_v2
- openstack_networking_port_v2
- openstack_networking_secgroup_v2
- openstack_networking_floatingip_v2
- openstack_networking_router_v2
- openstack_networking_trunk_v2

### References
- #453 
- #446 

@jtopjian should it be done within one PR or multiple?

**Comment by jtopjian** [comment]
Since it's a single line in each resource, one PR should be fine. We test tags on all resources, so if there's a problem, testing should reveal it.

If something goes awry, we might have to do separate PRs, but I don't anticipate that.

**Comment by jtopjian** [comment]
Upon thinking this over, I think this might be a case for `tags` (not computed / input) and `all_tags` (computed / output).

> In our openstack environment tags are added automatically by a backend network driver.

If you were to create a resource and apply one tag, then a tag is automatically set by the driver, you now have two tags. This would create a perpetual diff until you manually added the second tag to your configuration, right?

**Comment by kayrus** [comment]
> Upon thinking this over, I think this might be a case for tags (not computed / input) and all_tags (computed / output).

that's already done for data sources. `tags` are `Computed` and `all_tags` are `Optional`

> If you were to create a resource and apply one tag, then a tag is automatically set by the driver, you now have two tags. This would create a perpetual diff until you manually added the second tag to your configuration, right?

Right. Then it is a pain in the butt. It it very similar to what we discuss in the #574.Can we just keep #623 as simple as possible, and then we can try to find a solution within the #574.

**Comment by jtopjian** [comment]
> that's already done for data sources. 

Correct - that is what made me think of this scenario :slightly_smiling_face: 

> Right. Then it is a pain in the butt.

Now you're catching on :wink: 

> It is very similar to what we discuss in the #574.

I think this is different. #574 is about modifying an existing port. These network resources have _full_ control over the lifecycle of the resource, so when the resource is destroyed, _everything_ is gone. We don't need to worry about situations where only parts of the resource are removed.

IMO this is more similar to `openstack_networking_port_v2.security_group_ids` and `all_security_group_ids`.

However, this will raise the same situation as #552. 

> Can we just keep #623 as simple as possible, and then we can try to find a solution within the #574.

I'm not comfortable doing this. As you've seen with a lot of the issues opened, the solutions are difficult because they must take into consideration previous/legacy behavior. If we take the time to design something properly, it reduces issues in the long term.

Notably, as soon as something is marked as `Computed`, we're very restricted with how it can change from that point forward without making a breaking change. As long as something stays non-computed, we have room to work with it (this is why I mentioned I need extra time to look into #618).

**Comment by kayrus** [comment]
There could be three cases:

1. Ignore tags, when they're not set.
2. Rewrite tags, when they're set, even remove all the tags (empty set).
3. Append tags, when they're set.

All three cases could be solved by marking the field as `Computed`. But, the third case will require the `all_tags` and `append_tags` attributes.

When we do an update, we check `append_tags` and do a union of `tags` and `all_tags`, then update the tags. However, if we want to remove a particular tag, we cannot use something like `old_tags` for the initial tag status, because in my particular case, automatic tags are added within a few seconds delay and they could not be caught by terraform status refresh/read. And we cannot identify which tags were added by user, and which by Openstack env.

We can ignore the `remove tag` option, when `append_tags` is true and add a note in docs.

@jtopjian thought?

**Comment by kayrus** [comment]
Fortunately, tags have the `Set` schema, therefore we can apply the same set logic with the `enforce` flag we did in #574. Objections?

**Comment by jtopjian** [comment]
I think a feature like `enforce` is complementary to this - it won't solve the original issue of being able to set tags with an "input" field without it conflicting with tags being set on the server-side.

The only way that `enforce` would resolve this is if a user always chose `enforce` in situations where there was a tag being set on the server and they wanted to remove that tag.

If there is something wrong with using the pattern of `foo` and `all_foo` to handle this, I recommend looking at a larger provider like AWS to see how similar issues are handled.

**Comment by kayrus** [comment]
If you want to omit enforce flag, I'm ok with this. I renamed the #623 and pushed new changes, please have a look and let me know what do you think.

**Comment by jtopjian** [comment]
> If you want to omit enforce flag, I'm ok with this

Just to clarify: I'm not opposed to an enforce flag. I think it's something which would be in addition to this and could be implemented afterwards. If a user chooses not to use enforce, then the original problem that #623 is solving still exists.

> I renamed the #623 and pushed new changes, please have a look and let me know what do you think.

Perhaps it is due to finally not being jet-lagged and/or actually sleeping, but `networkV2ReadAttributesTags` makes a lot of sense. I think you've come across the final piece in making these situations (having user input and server-side input coexist) manageable.

It's allowing a diff to be triggered only if the user-supplied input didn't exist on the resource which is what we want. The addition of some enforce behavior (and again, this can wait) would modify this to overwrite/clobber what the server set. I think this all works out nicely.
