### ISSUE TITLE
Add possibility to list available availability zones

### ISSUE THREAD

**Issue by kayrus** [terraform-providers/terraform-provider-openstack#651]
In order when user wants to create multiple clusters bound to the availability zone, it would be great to fetch the list of availability zones as a data source.

### Affected Data Source(s)

- openstack_availability_zones

**Comment by jtopjian** [comment]
@kayrus 

Since this is about the design of the data sources, I'm moving the conversation here.

> For HA deployments, scaled accross multiple regions. Some regions have different amount of AZ. For sure, they can be specified manually in a list, but if it can be automated, I'd automate it, especially when you have more than 10 regions. Do you have other thoughts?

Right, but is a plain, unfiltered list good enough or useful?

The reason this needs to be a separate data source per API/project is because AZ details can appear differently and be used differently from service to service. In that regards, you'll want to take a look at each kind of AZ feature and what information each of them contains. Can an SFS AZ be filtered in any way?

**Comment by kayrus** [comment]
It could be filtered for compute and storage AZs by using the `available` bool field, but I doubt it is reasonable. As for the SFS, there is nothing I can see, that could be filtered.

Although, for instance, I have cases, when SFS has only one AZ, but compute service has 4. AZs could be filtered by a list of zones as an input.

**Comment by kayrus** [comment]
@jtopjian, you've just raised a good case about the ordering. For instance, I have the following AZs:

compute/storage:
* zone-a
* zone-b
* zone-c (unavailable)
* zone-d

sfs:
* zone-d

Let's assume terraform manifest uses all zones without any limits, and one day `zone-c` becomes available, then zone-d appears to be 4th zone, and zone-c appears to be 3rd one and replaces zone-d. Simple terraform manifest will re-create all the resources inside zone-d and will create new resources inside zone-c.

Then, for instance, we have SFS. One day new `a-c` zones appear and openstack returns these zones in the alphabetical order. Zone-d resources will be recreated again.

I'm not sure how is it possible to avoid unnecessary resources re-creation without using maps.

/cc @twexler

**Comment by twexler** [comment]
So, the goal I had with #655 was to approximate the usage of `aws_availability_zones` wherein there is a datasource that you can use in your manifests to acquire a list of AZs based on availability (capacity, etc) and use that data inside of resources.

I did implement the filtering on `ZoneState` in that PR but did not consider ordering. 

FWIW: We don't have a similar constraint in our use case (people adding new zones in the wrong order), hence the lack of sorting. We also don't use `SharedFileSystem` so that wasn't a consideration for me.

**Comment by jtopjian** [comment]
Ordering was another issue I had in mind, but I didn't want to add too much complication to the discussion off the bat. This is another reason why I'm shy with data sources that can't filter deterministically or return more than one result (to be clear, I'm not opposed, I'm just hesitant with them).

The AWS provider does indeed have a similar data source and if users are happily using that without consideration to ordering, then I'm OK with that. 

In addition, the situations that arise when trying to use multiple AZs (ie compute+sfs) are indeed complicated. Terraform being able to return a list of AZs using independent data sources and having the user figure out the right combination to use is probably the best approach.
