### ISSUE TITLE
LBAAS resources fail to be properly created with OpenStack provider > v1.13

### ISSUE THREAD

**Issue by pblaas** [terraform-providers/terraform-provider-openstack#762]
### Terraform Version
provider.openstack v1.19.0
Terraform v0.12.0

### Affected Resource(s)
Please list the resources as a list, for example:
- openstack_lb_monitor_v2
- openstack_lb_member_v2
- openstack_lb_pool_v2

### Terraform Configuration Files
https://gist.github.com/pblaas/dfda651e3426832f128a9eedec3401ba

### Debug Output
https://gist.github.com/pblaas/d5f910f6037e926ce3e427053973c245

### Expected Behavior
Sequential runs should not end up in error.

### Actual Behavior
Sequential runs run into error with LBAAS resources.

```
  # openstack_lb_monitor_v2.k8scluster_monitor_1 must be replaced
-/+ resource "openstack_lb_monitor_v2" "k8scluster_monitor_1" {
        admin_state_up = true
        delay          = 30
      + expected_codes = (known after apply)
      + http_method    = (known after apply)
      ~ id             = "e2950c14-f2d3-47c6-a186-84664bd1cfeb" -> (known after apply)
        max_retries    = 10
      ~ name           = "e2950c14-f2d3-47c6-a186-84664bd1cfeb" -> "k8scluster_monitor_1"
      + pool_id        = "167a7157-8c3d-48e8-9368-0e65095ece96" # forces replacement
      ~ region         = "AMS" -> (known after apply)
      ~ tenant_id      = "ce14d528032f49d2aface34409ad363b" -> (known after apply)
        timeout        = 10
        type           = "PING"
      + url_path       = (known after apply)
    }

Plan: 1 to add, 0 to change, 1 to destroy.
```
```
openstack_lb_monitor_v2.k8scluster_monitor_1: Destroying... [id=e2950c14-f2d3-47c6-a186-84664bd1cfeb]
Error: Unable to retrieve parent pool () for the monitor: Resource not found
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`
2. `terraform apply`

### Important Factoids
OpenStack is using OpenContrail networking. 
This was working with older versions of OpenStack provider.

**Comment by kayrus** [comment]
Probably there is a bug in the OpenContrail implementation. It should send `id`, but it sends `pool_id`. Gophercloud expects to see `id`: https://github.com/gophercloud/gophercloud/blob/b8b6f3e2be05908d2c212e3588f16e3a2eba4530/openstack/networking/v2/extensions/lbaas_v2/monitors/results.go#L9

In your example, opencontrail returns:

```json
{ 
  "healthmonitor": { 
    "admin_state_up": true, 
    "delay": 30, 
    "id": "e2950c14-f2d3-47c6-a186-84664bd1cfeb", 
    "max_retries": 10, 
    "name": "e2950c14-f2d3-47c6-a186-84664bd1cfeb", 
    "pools": [ 
      { 
        "pool_id": "167a7157-8c3d-48e8-9368-0e65095ece96" 
      } 
    ], 
    "tenant_id": "ce14d528032f49d2aface34409ad363b", 
    "timeout": 10, 
    "type": "PING" 
  } 
}
```

However in my environment I get:

```json
{
  "healthmonitor": {
    "name": "mypool",
    "pools": [
      {
        "id": "040143da-c994-49e1-b5b4-023ea60c23a2"
      }
    ],
    "admin_state_up": true,
    "tenant_id": "a47d1a25b00f41c9ab0bd98225fb4655",
    "delay": 5,
    "max_retries": 3,
    "timeout": 2,
    "max_retries_down": 3,
    "project_id": "a47d1a25b00f41c9ab0bd98225fb4655",
    "type": "PING",
    "id": "39f1d867-d32c-40aa-a8c9-047b7148f72d"
  }
}
```

It worked before, because resource import was not supported and `pool_id` was not updated from the API response. Once the import feature was added, openstack provider started to consider response data:
https://github.com/terraform-providers/terraform-provider-openstack/commit/cf00823e8#diff-7c37d01153fe298bf2dbe42d13109944R173
There is a check to identify whether struct is not empty, however in your case struct has `len > 0`, but the ID is empty...

**Comment by pblaas** [comment]
@kayrus Thanks for the fix, works great!
