### ISSUE TITLE
Refreshing an instance that have an attached port (without refreshing the port) do not detach the port interface before deleting the instance

### ISSUE THREAD

**Issue by dhiaayachi** [terraform-providers/terraform-provider-openstack#858]
### Terraform Version
v0.12.7

### Affected Resource(s)
- openstack_compute_instance_v2

### Terraform Configuration Files
```tf
resource  "openstack_compute_instance_v2"  "zookeeper" {

    name           = "test"
    image_id        = "${var.image_id}"
    flavor_name       = "${var.flavor}"
    key_pair        = "${var.key_pair_name}"

  network {
    port = "${var.port_id}"
  }
  stop_before_destroy = true
}
```

### Debug Output
 Error creating OpenStack server: Expected HTTP response code [] when accessing [POST http://10.0.0.1:8774/v2.1/64b75fdb8a5b403cbfb2166d6f82c5f3/servers], but got 409 instead
{"conflictingRequest": {"message": "Port e9a37693-314f-4273-a822-a93aab3c73f4 is still in use.", "code": 409}}

### Expected Behavior
Port need to be detached correctly and reattached to the new instance

### Actual Behavior
the instance refresh delete the vm and rely on openstack to detach the port from it, this is not a good openstack practice as the port detaching api call in that case is async and could lead to an error which make the port unusable (attached to an instance that do not exist)

### Steps to Reproduce
Use an existing port (not part of the terraform definition) hardcode the port id in an instance as above
1. `terraform apply`
2. `change params in the instance definition
3 `terraform apply`

**Comment by kayrus** [comment]
@dhiaayachi don't you have a typo here?

```hcl
  network {
    port = "${var.key_pair_name}"
  }
```

**Comment by dhiaayachi** [comment]
Indeed!! Copy paste :D, I will fix that.

**Comment by dhiaayachi** [comment]
This an attempt to fix the issue, I tested it with an on-prem openstack project and it work as expected. Please comment.

**Comment by ozerovandrei** [comment]
I left some comments in the PR.

I also don't think that every user needs that since OpenStack detaches ports while deleting instance. 
You can run into issue while hardcoding `port_id` and recreating instance from the same manifest but many users don't need that since there haven't been similar issues yet.

I guess it's better to introduce the `detach_ports_before_destroy` argument for the instance resource and use it similar to `stop_before_destroy` and `force_delete` in `resourceComputeInstanceV2Delete()`.
This argument should go into the `vendor_options` same as `ignore_resize_confirmation` since we add all new vendor-specific options there.

**Comment by dhiaayachi** [comment]
Thank you for the comments, I did the changes requested on the PR and I will continue to work on it to introduce a new flag for `detach_ports_before_destroy`
