### ISSUE TITLE
Glance V2: Add image sharing resource

### ISSUE THREAD

**Issue by kayrus** [terraform-providers/terraform-provider-openstack#869]
### Affected Resource(s)
- openstack_images_image_share_v2
- openstack_images_share_v2

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
resource "openstack_images_image_v2" "rancheros" {
  name             = "RancherOS"
  image_source_url = "https://releases.rancher.com/os/latest/rancheros-openstack.img"
  container_format = "bare"
  disk_format      = "qcow2"
  visibility = "shared"

  properties = {
    key = "value"
  }
}

resource "openstack_images_image_share_v2" "rancheros" {
  image_id = "${openstack_images_image_v2.rancheros.id}"
  member_id = "%projectid%"
  status = "pending" # for the %projectid% context only
}
```

### Expected Behavior

Image owner has to have an ability to share an image with other projects/users.

### Important Factoids

User has to approve the image on his end, nevertheless user can already use the image with the `pending` status by using its id.

@ozerovandrei @jtopjian please give me a hint for the resource name:
* openstack_images_image_share_v2
* openstack_images_share_v2
* openstack_images_image_member_v2
* ???

Target user can list the shared image using the data source (probably the #139 will be helpful here as well.):

```hcl
data "openstack_images_image_v2" "ubuntu" {
  visibility = "shared"
  member_status = "pending"
}
```

then approve/decline the image membership, probably using the same terraform resource.

Target use case:

* create a project
* share an image from the source project
* auth within the target project scope
* accept the shared image

### References

https://github.com/gophercloud/gophercloud/blob/c1ae5ed189fea28b1222fb6f9d4daf80471e2855/openstack/imageservice/v2/members/results.go
#860 
https://github.com/hashicorp/terraform/issues/16967

**Comment by kayrus** [comment]
I performed some tests and it is better to split one resource into two resources:
* `openstack_images_image_share_producer_v2`
* `openstack_images_image_share_consumer_v2`

according to the http://specs.openstack.org/openstack/glance-specs/specs/api/v2/sharing-image-api-v2.html terminology.

**Comment by jtopjian** [comment]
> openstack_images_image_share_producer_v2

Is this the same as `openstack_images_image_v2` with a status/visibility of "shared"?

`openstack_images_image_member_v2` sounds good to me. Ideally this would have `image_id` and `member_id` (`project_id`) arguments. The resource will probably need to loop through all members to find a match, but I think we do that in some other resources, anyway. It can have a computed attribute of `status`, too, I think.

**Comment by kayrus** [comment]
> Is this the same as `openstack_images_image_v2` with a status/visibility of "shared"?

The image owner has to create an image first with the `shared` status, then it has to propose this image to the destination target using the `/members` api route.

Once the target member id is proposed, then the target project ID can use the image using its id. But if you want to list the shared image without any additional filters, then the image has to be accepted. The accept API call consists of PUT method to the `/members` api route.

To conclude, do you propose two resource names?

* `openstack_images_image_member_v2` for the image owner
* `openstack_images_image_consumer_v2` for the target project

**Comment by jtopjian** [comment]
Right. 

Unless @ozerovandrei gets to it first, I'll think about how this might best work when I get some time. 

As you've described, the sharing workflow involves some back-and-forth. For `$work` we ended up writing an admin-only workflow that is able to assign images to members to bypass a lot of this.

**Comment by kayrus** [comment]
> As you've described, the sharing workflow involves some back-and-forth. For $work we ended up writing an admin-only workflow that is able to assign images to members to bypass a lot of this.

Unfortunately an admin scope is not always supported.

**Comment by jtopjian** [comment]
Oh, sorry - I agree 100%.

I was just mentioning that to illustrate that it's a complicated process that we were able to avoid 🙂 Proper modeling of this in Terraform will take some thought.

**Comment by jtopjian** [comment]
I _think_ this will work.

These two scenarios involve two new resources:

* `openstack_images_image_share_v2`: This has the role of "producer" in the OpenStack docs.
* `openstack_images_image_share_accept_v2`: This has the role of "consumer" in the OpenStack docs.

### Scenario 1: Admin shares an image to a project

```hcl
resource "openstack_images_image_v2" "rancheros" {
  name             = "RancherOS"
  image_source_url = "https://releases.rancher.com/os/latest/rancheros-openstack.img"
  container_format = "bare"
  disk_format      = "qcow2"

  visibility       = "shared"
}

resource "openstack_images_image_share_v2" "rancheros" {
  image_id = "${openstack_images_image_v2.rancheros.id}"
  member   = "<project_id>"
  status   = "accepted"
}
```

This allows an admin user to share an image and grant access to the image all at once. In the schema, `status` will have a default value of `pending`. During the `Create` function, if `status` is not `pending`, then both `members.Create` (to add the project to the membership list) and `members.Update` (to set the status to accepted) will be called .

### Scenario 2: Admin or Project offers an image to share

#### Admin or Project 1

```hcl
resource "openstack_images_image_v2" "rancheros" {
  name             = "RancherOS"
  image_source_url = "https://releases.rancher.com/os/latest/rancheros-openstack.img"
  container_format = "bare"
  disk_format      = "qcow2"

  visibility       = "shared"
}

resource "openstack_images_image_share_v2" "rancheros" {
  image_id = "${openstack_images_image_v2.rancheros.id}"
  member   = "<project_id>"
}
```

#### Project 2

```hcl
data "openstack_images_image_v2" "rancheros" {
  name       = "rancheros"
  visibility = "shared"
}

resource "openstack_images_image_share_accept_v2" "rancheros" {
  image_id = "${data.openstack_images_image_v2.rancheros.id}"
  member   = "<project_id>"
  status   = "accepted"
}
```

`openstack_images_image_share_accept_v2` only implements the `members.Update` function in Gophercloud, during both Terraform's `Create` and `Update` functions.

In the schema, the default value of `status` can be `accepted`. The user can optionally change this to `rejected` if they feel the need. 

I guess the `Delete` function in Terraform is effectively a no-op and just removes the resource from state? This is because there's no way for the consumer of an image share to remove their own membership from the image list. They can change the status to `rejected`, but that's not really a delete action because they can revert the status to `pending` or `accepted` if they'd like (I think). This needs tested.

Only `openstack_images_image_share_v2` has an actual `Delete` function in Terraform.

**Comment by kayrus** [comment]
@jtopjian so you propose `openstack_images_image_share_v2` and `openstack_images_image_share_accept_v2`? And as I see the `member` instead of the `member_id`, right?

> I guess the Delete function in Terraform is effectively a no-op and just removes the resource from state? This is because there's no way for the consumer of an image share to remove their own membership from the image list. They can change the status to rejected, but that's not really a delete action because they can revert the status to pending or accepted if they'd like (I think). This needs tested.

From the user perspective, if s/he destroys the `openstack_images_image_share_accept_v2` resource, s/he expects that the image should not be available anymore. Setting the `rejected` status on destroy fits well on this pattern. I tested, user can accept, then decline, then accept again the membership status.

**Comment by jtopjian** [comment]
> And as I see the member instead of the member_id, right?

Either one. `member` is what the API uses, but `member_id` is more descriptive.

> From the user perspective, if s/he destroys the openstack_images_image_share_accept_v2 resource, s/he expects that the image should not be available anymore.

I agree. But the API does not support this on the consumer side. The consumer is unable to delete their entry from the membership list. It's a weird set of API calls.

**Comment by jtopjian** [comment]
oops

> Setting the rejected status on destroy fits well on this pattern.

Yes, this is the best we can do. `rejected` will act like a faux-delete call. This also allows the appearance of being able to recreate the resource.

**Comment by kayrus** [comment]
@jtopjian so what about the #872? Do I need to add extra changes or adding the extra docs from the https://github.com/terraform-providers/terraform-provider-openstack/issues/869#issuecomment-532933988 is enough?

**Comment by jtopjian** [comment]
I think any names chosen for these resources is going to have pros and cons. It's really hard to determine good names for this scenario. I believe I saw an AWS resource with the name "accept" in it, which is why I used it. But totally up to you guys on the final decision.

I did a quick scan of the logic and it all looks good to me. The `Create` and `Delete` functions of both look correct.

**Comment by kayrus** [comment]
@jtopjian will rename the resources to fit the https://www.terraform.io/docs/providers/openstack/r/compute_flavor_access_v2.html concept:

* `openstack_images_image_access_v2`
* `openstack_images_image_access_accept_v2`
