### ISSUE TITLE
Some help on understanding terraform API mechanism

### ISSUE THREAD

**Issue by pkqsun** [terraform-providers/terraform-provider-openstack#917]
### Current Issue for me

We set up a local private OpenStack lab and normally it works well.
However, when we creating a large number of instance (about 100 nodes), it always failed with failure somehow ( the resource is enough).

OpenStack Configurations:
```
/etc/haproxy/haproxy.cfg:
defaults
  log  global
  maxconn  4096      <====   we could increase to 16384
  mode  tcp
  retries  3

/etc/keystone/keystone.conf:
expiration = 3600    <===  1h 
```

So I got some confusion on the API mechanism for Terraform:

1)  What does "-parallelism=n" in apply cmd means exactly? is it the concurrent API request of sub-resources ? 10 default concurrent operation will send 10 API requests at a same time by Terraform?

2) I know Terraform will resolve the resource dependences. But how does Terraform check the dependences are satisfied for one instance? 

3) When one API request is sent, does terraform check the response whether it finished successfully or not ? If so, failed API request will lead another retry request ?

4)  For openstack provider, does terreform handle the API rate limitation? I mean if too much API request are sent to OpenStack, how does Terraform handle it ?

Appreciate for any explanation or useful links !

**Comment by kayrus** [comment]
@pkqsun thanks for your questions.

1. `-parallelism=n` means how many terraform resources are processed at once (not API calls).
2. If the dependent resources were successfully provisioned, then it means that the instance resource can be provisioned.
3. Terraform checks failed resources, but it will still try to process the new resources and those which are still provisioning. Once all the resources are done, succeeded or failed, terraform will print the final result.
4. Terraform can retry the failed TCP connection. But if there is a failed HTTP response, it won't retry, unless it is coded explicitly, e.g. handling 409 code in lbaas resources.

From the long-running terraform resource provisioning perspective, I believe there should be an option to allow re-auth, because terraform shares one authed client (e.g. one token) with other service clients during the provider process lifetime. And if there is a number of long-running resources, e.g. 100 VMs, it's worth to have this option.

**Comment by pkqsun** [comment]
@kayrus ,

Thanks a lot for your comments.
We will check the token TTL expire timeout in our OpenStack.
