### ISSUE TITLE
Block Storage: new data resource for volume

### ISSUE THREAD

**Issue by Shonei** [terraform-providers/terraform-provider-openstack#925]
Hi there,

We are looking into adding a new data resource for volumes.

### Terraform Version
Terraform v0.12.9
provider.openstack v1.23.0

### Affected Resource(s)
openstack_blockstorage_volume_v2

The argument list we are thinking of is:

- region
- name
- state
- metadata
- bootable
- volume_type

And here are the attributes that will get computed:
 - size
 - id
 - source_volume_id

Does this seem acceptable ot should we change some of the parameters.

**Comment by ozerovandrei** [comment]
Any PRs are welcome.

I guess that it will be also possible to implement `openstack_blockstorage_volume_v3` in the same way you will implement `openstack_blockstorage_volume_v2` since their `List()` method and options are similar.

https://github.com/gophercloud/gophercloud/blob/master/openstack/blockstorage/v2/volumes/requests.go#L113
https://github.com/gophercloud/gophercloud/blob/master/openstack/blockstorage/v3/volumes/requests.go#L115

**Comment by Shonei** [comment]
Should I include the v2 and v3 in a single pull request.
Also for `bootable` and `volume_type` they are not options in the API but I can filter once I get a list of volumes. Should they be options for retrieving volumes or only part of the return attributes.

**Comment by ozerovandrei** [comment]
@Shonei it's better to split PRs for different datasources.

Sure you can filter all results for needed arguments. We already doing this in some other datasources like `compute_flavor_v2`.

**Comment by Shonei** [comment]
As both PR have been merged I will close this.
