### ISSUE TITLE
Feature request: support the extra_dhcp_opts parameter for the port resource 

### ISSUE THREAD

**Issue by ghost** [terraform-providers/terraform-provider-openstack#99]
### Affected Resource(s)
- openstack_networking_port_v2

### Actual Behavior
There is no extra_dhcp_opts in the schema of the resourceNetworkingPortV2.
As the Neutron API expects a list of maps for the extra_dhcp_opts parameter it is currently not possible to provide the value via the value_specs parameter (which only accepts strings for the parameter values)

### Expected Behavior
There is a way to provida a value for the extra_dhcp_opts parameter when creating or updating the port resource

**Comment by fatmcgav** [comment]
@salikov-201511 At a quick glance, it looks like `extra_dhcp_opts` is also missing from the Gophercloud [port package](https://github.com/gophercloud/gophercloud/tree/master/openstack/networking/v2/ports). 

So support would need to be added to the Gophercloud library before we could add it into the `openstack` provider. 

If you feel up for it, PR's are welcome both here and upstream in Gophercloud.
Otherwise hopefully someone will be able to get to it soon...

**Comment by salikov-201511** [comment]
@fatmcgav Thanks. Unfortunately I won't be able to produce a PR for this anytime soon as I have zero experience with Go language. Hopefully someone will be able to implement this.

**Comment by jtopjian** [comment]
This was added in #258
